window.i18nData={
        "invalid_email":"يرجى إدخال عنوان بريد إلكتروني صالح",
        "invalid_fname":"الاسم الأول غير صالح.",
        "invalid_lname":"اسم العائلة غير صالح.",
        "invalid_phone":"رقم الهاتف غير صالح.",
        "invalid_cc_month":"شهر انتهاء صلاحية البطاقة غير صالح.",
        "invalid_cc_year":"سنة انتهاء صلاحية البطاقة غير صالحة.",
        "invalid_cc":"رقم بطاقة الائتمان غير صالح.",
        "invalid_cvv":"رمز التحقق من البطاقة غير صالح.",
        "invalid_billing_fname":"الاسم الأول في معلومات الفوترة غير صالح.",
        "invalid_billing_lname":"اسم العائلة في معلومات الفوترة غير صالح.",
        "terms_agree":"يرجى الموافقة على الشروط والأحكام.",
        "required_fields":"الحقول المطلوبة مميزة باللون الأحمر",
        "required_fields2":"يرجى تعبئة الحقول المطلوبة المميزة باللون الأحمر.",
        "no_orders":"لا توجد طلبات.",
        "decline":"يقوم بنكك بحظر هذه الدفعة. يرجى البقاء في هذا المتصفح و<b>الرد على رسالة البنك النصية أو البريد الإلكتروني لإتمام هذا الطلب</b>. يرجى التحقق من معلوماتك والمحاولة مرة أخرى أو استخدام طريقة دفع مختلفة.<br/><br/>السبب:",
        "no_item_in_cart":"لا توجد عناصر في سلة التسوق. يرجى تحديد طلبك.",
        "page_reload":"ستُعاد تحميل الصفحة بعد إغلاق مربع الحوار.",
        "invalid_exp_month":"يرجى إدخال شهر صالح",
        "invalid_exp_year":"يرجى إدخال سنة صالحة.",
        "redirect_to_next":"جارٍ التحويل إلى الصفحة التالية.",
        "processing":"جارٍ معالجة الطلب...",
        "paypal_processing":"يرجى الانتظار بينما نقوم بتحويلك إلى PayPal Checkout...",
        "loading_msg":"جارٍ حجز منتجك",
        "loading_msg_header":"يرجى الانتظار لحظة",
        "select":"اختر",
        "month":"الشهر",
        "year":"السنة",
        "january":"01 (يناير)",
        "february":"02 (فبراير)",
        "march":"03 (مارس)",
        "april":"04 (أبريل)",
        "may":"05 (مايو)",
        "june":"06 (يونيو)",
        "july":"07 (يوليو)",
        "august":"08 (أغسطس)",
        "september":"09 (سبتمبر)",
        "october":"10 (أكتوبر)",
        "november":"11 (نوفمبر)",
        "december":"12 (ديسمبر)",
        "klarna_billing_information":"معلومات الفوترة",
        "klarna_email_placeholder":"عنوان البريد الإلكتروني المفضل",
        "klarna_fname_placeholder":"الاسم الأول",
        "klarna_lname_placeholder":"اسم العائلة",
        "klarna_address1_placeholder":"عنوان الشارع",
        "klarna_address2_placeholder":"رقم الشقة / الجناح / أخرى",
        "klarna_city_placeholder":"المدينة",
        "klarna_state_province":"-- اختر الولاية / المقاطعة --",
        "klarna_postal_code":"الرمز البريدي",
        "klarna_continue_with_text":"المتابعة مع",
        "trust_rating_popup_headertext":"كيف تقيّم تجربة التسوق الخاصة بك؟",
        "trust_rating_popup_subtext":"رأيك يعني لنا الكثير",
        "trust_rating_buttontext":"إرسال",
        "required":"حقل مطلوب",
        "invalid_exp_date":"تاريخ انتهاء الصلاحية غير صالح",
        "error-msg-header":"فشلت عملية الدفع. يرجى التحقق من بياناتك أو استخدام طريقة دفع مختلفة.<br/><br/>السبب (الأسباب):",
        "wallet-payment-phone-header":"يرجى تعبئة الحقل (الحقول) المطلوبة أدناه لضمان توصيل سلس وناجح لطلبك.",
        "wallet-payment-submit-text":"إرسال",
        "invalid_cpf":"يرجى إدخال رقم CPF صالح.",
        "invalid_houseno":"يرجى إدخال رقم المنزل.",
        "invalid_bairro":"يرجى إدخال Bairro.",
        "invalid_neighborhood":"يرجى إدخال اسم الحي.",
        "something_wrong":"حدث خطأ ما. ",
        "retry":"إعادة المحاولة",
        "invalid_consigneeId":"معرّف المرسَل إليه غير صالح",
        "phone_number":"رقم الهاتف:",
        "consignee_id":"معرّف المرسَل إليه:",
        "cpf":"CPF (سجل دافع الضرائب الفردي):",
        "pccc":"PCCC (رمز التخليص الجمركي الشخصي):",
        "invalid_code_id":"الرمز أو المعرّف غير صالح",
        "paymentMethod_not_return":"لم يتم إرجاع معرّف طريقة الدفع. يرجى المحاولة مرة أخرى لاحقاً.",
        "invalid_tax_id":"الرمز أو الرقم الضريبي غير صالح",   
        'invalid_district': 'يرجى إدخال المنطقة',
        'invalid_village': 'يرجى إدخال القرية',
        'invalid_apt_unit': 'يرجى إدخال رقم الشقة/الوحدة',
        'invalid_county': 'يرجى إدخال المقاطعة',
        'invalid_ward': 'يرجى إدخال الحي',
        'invalid_address1': 'يرجى إدخال العنوان',
        'unable_to_load_suggestions': 'تعذر تحميل الاقتراحات',
        'searching': 'جارٍ البحث...',
        "record_not_found": "لم يتم العثور على السجل",
        "invalid_zip_no": "4 أرقام.",
        "invalid_city_no": "أدخل الرمز البريدي أولاً.",
        "invalid_address_1_no": "أدخل عنوان الشارع ورقم المنزل.",
        "invalid_zip_lu": "4 أرقام.",
        "invalid_city_lu": "أدخل الرمز البريدي أولاً.",
        "invalid_address_1_lu": "أدخل الرقم واسم الشارع."
}