window.i18nData={
        "invalid_email":"Zadejte prosím platnou e-mailovou adresu.",
        "invalid_fname":"Neplatné jméno.",
        "invalid_lname":"Neplatné příjmení.",
        "invalid_phone":"Neplatné telefonní číslo.",
        "invalid_cc_month":"Neplatný měsíc expirace karty.",
        "invalid_cc_year":"Neplatný rok expirace karty.",
        "invalid_cc":"Neplatné číslo kreditní karty.",
        "invalid_cvv":"Neplatný ověřovací kód karty (CVV).",
        "invalid_billing_fname":"Neplatné fakturační jméno.",
        "invalid_billing_lname":"Neplatné fakturační příjmení.",
        "terms_agree":"Prosím, souhlaste s našimi obchodními podmínkami.",
        "required_fields":"Povinná pole jsou zvýrazněna červeně",
        "required_fields2":"Prosím, vyplňte povinná pole zvýrazněná červeně.",
        "no_orders":"Žádné objednávky.",
        "decline":"Vaše banka blokuje tuto platbu. Zůstaňte v tomto prohlížeči a <b>ODPOVĚZTE NA SMS NEBO E-MAIL OD BANKY PRO DOKONČENÍ OBJEDNÁVKY</b>. Ověřte své údaje a zkuste to znovu, nebo použijte jiný způsob platby.<br/><br/>Důvod:",
        "no_item_in_cart":"V košíku nemáte žádné položky. Prosím, vyberte si svou objednávku.",
        "page_reload":"Stránka se po zavření dialogového okna znovu načte.",
        "invalid_exp_month":"Prosím, zadejte platný měsíc.",
        "invalid_exp_year":"Prosím, zadejte platný rok.",
        "redirect_to_next":"Přesměrování na další stránku.",
        "processing":"Zpracování požadavku...",
        "paypal_processing":"Prosím, vyčkejte, přesměrováváme vás na platbu PayPal...",
        "loading_msg":"Váš produkt je rezervován",
        "loading_msg_header":"Prosím, počkejte chvíli",
        "select":"Vybrat",
        "month":"Měsíc",
        "year":"Rok",
        "january":"01 (Led)",
        "february":"02 (Úno)",
        "march":"03 (Bře)",
        "april":"04 (Dub)",
        "may":"05 (Kvě)",
        "june":"06 (Čvn)",
        "july":"07 (Čvc)",
        "august":"08 (Srp)",
        "september":"09 (Zář)",
        "october":"10 (Říj)",
        "november":"11 (Lis)",
        "december":"12 (Pro)",
        "klarna_billing_information":"Fakturační údaje",
        "klarna_email_placeholder":"Preferovaná e-mailová adresa",
        "klarna_fname_placeholder":"Jméno",
        "klarna_lname_placeholder":"Příjmení",
        "klarna_address1_placeholder":"Ulice a číslo popisné",
        "klarna_address2_placeholder":"Byt / Apartmán / Jiné",
        "klarna_city_placeholder":"Město",
        "klarna_state_province":"-- Vyberte kraj --",
        "klarna_postal_code":"PSČ",
        "klarna_continue_with_text":"Pokračovat s",
        "trust_rating_popup_headertext":"Jak byste ohodnotili svůj nákupní zážitek?",
        "trust_rating_popup_subtext":"Váš názor pro nás hodně znamená",
        "trust_rating_buttontext":"Odeslat",
        "required":"Povinné pole",
        "invalid_exp_date":"Neplatné datum expirace",
        "error-msg-header":"Platba se nezdařila. Ověřte své údaje nebo použijte jiný způsob platby.<br/><br/>Důvod(y):",
        "wallet-payment-phone-header":"Prosím, vyplňte níže uvedená povinná pole pro zajištění hladkého a úspěšného doručení vaší objednávky.",
        "wallet-payment-submit-text":"Odeslat",
        "invalid_cpf":"Prosím, zadejte platné číslo CPF.",
        "invalid_houseno":"Prosím, zadejte číslo domu.",
        "invalid_bairro":"Prosím, zadejte čtvrť (Bairro).",
        "invalid_neighborhood":"Prosím, zadejte čtvrť.",
        "something_wrong":"Něco se pokazilo. ",
        "retry":"Zkusit znovu",
        "invalid_consigneeId":"Neplatné ID příjemce",
        "phone_number":"Telefonní číslo:",
        "consignee_id":"ID příjemce:",
        "cpf":"CPF (Registr fyzických osob):",
        "pccc":"PCCC (Osobní celní odbavovací kód):",
        "invalid_code_id":"Neplatný kód nebo ID",
        "paymentMethod_not_return":"ID platební metody nebylo vráceno. Prosím, zkuste to znovu později.",
        "invalid_tax_id": "Neplatný kód nebo DIČ",
        'invalid_district': 'Zadejte okres',
        'invalid_village': 'Zadejte obec',
        'invalid_apt_unit': 'Zadejte číslo bytu/jednotky',
        'invalid_county': 'Zadejte kraj',
        'invalid_ward': 'Zadejte městskou část',
        'invalid_address1': 'Zadejte adresu',
        'unable_to_load_suggestions': 'Návrhy se nepodařilo načíst',
        'searching': 'Vyhledávání...',
        "record_not_found": "Záznam nebyl nalezen",
        "invalid_zip_no": "4 číslice.",
        "invalid_city_no": "Nejprve zadejte PSČ.",
        "invalid_address_1_no": "Zadejte adresu a číslo domu.",
        "invalid_zip_lu": "4 číslice.",
        "invalid_city_lu": "Nejprve zadejte PSČ.",
        "invalid_address_1_lu": "Zadejte číslo a název ulice.",
        "invalid_address_gr": "Zadejte svou adresu.",
        "invalid_zip_gr": "5 číslic.",
        "invalid_city_gr": "Vstupte do města.",
        "invalid_address_rs": "Zadejte název ulice a číslo domu.",
        "invalid_zip_rs": "5 číslic.",
        "invalid_city_rs": "Zadejte název města.",
        "invalid_address_ch": "Zadejte prosím název ulice a číslo domu.",
        "invalid_zip_ch": "4 číslice.",
        "invalid_city_ch": "Zadejte prosím město.",
        "invalid_value_zh_hant": "Zadejte svou adresu v tradiční čínštině."
}