window.i18nData={
        "invalid_email":"Please enter a valid email address", 
        "invalid_fname":"Invalid First Name.", 
        "invalid_lname":"Invalid Last Name.", 
        "invalid_phone":"Invalid Phone Number.", 
        "invalid_cc_month":"Invalid Card Expiration Month.", 
        "invalid_cc_year": "Invalid Card Expiration Year.", 
        "invalid_cc":"Invalid Credit Card Number.", 
        "invalid_cvv":"Invalid Card Verification Value.", 
        "invalid_billing_fname":"Invalid Billing First Name.", 
        "invalid_billing_lname":"Invalid Billing Last Name.", 
        "terms_agree":"Please agree to our terms and conditions.",
        "required_fields":"Required field(s) highlighted in red", 
        "required_fields2" :"Please fill up required fields highlighted in red.", 
        "no_orders":"There are no orders.",
        "decline": "Your bank is blocking this payment. Please stay on this browser and <b>RESPOND TO THE BANK SMS OR EMAIL TO COMPLETE THIS ORDER</b>. Please verify your info and try again or use a different payment method.<br/><br/>Reason:", 
        "no_item_in_cart": "There are no items on your cart. Please select your order.", 
        "page_reload":"The page will reload after you close the dialog.",
        "invalid_exp_month":"Please enter a valid month", 
        "invalid_exp_year":"Please enter a valid year.", 
        "redirect_to_next":"Redirecting to the next page.",
        "processing":"Processing request...", 
        "paypal_processing":"Please wait as we redirect you to PayPal Checkout...", 
        "loading_msg":"Your Product Is Being Reserved",
        "loading_msg_header": "Please wait a moment",
        "select": "Select", 
        "month" : "Month", 
        "year" : "Year",
        "january":"01 (Jan)",
        "february":"02 (Feb)",
        "march":"03 (Mar)",
        "april":"04 (Apr)",
        "may":"05 (May)",
        "june":"06 (Jun)",
        "july":"07 (Jul)",
        "august":"08 (Aug)",
        "september":"09 (Sep)",
        "october":"10 (Oct)",
        "november":"11 (Nov)",
        "december":"12 (Dec)",
        "klarna_billing_information": "Billing Information",
        "klarna_email_placeholder":"Preferred Email Address",
        "klarna_fname_placeholder":"First Name",
        "klarna_lname_placeholder":"Last Name",
        "klarna_address1_placeholder":"Street Address",
        "klarna_address2_placeholder" :"Apt / Suite / Other",
        "klarna_city_placeholder" :"City",
        "klarna_state_province" :"-- Select State / Province --",
        "klarna_postal_code" :"Zip / PostalCode",
        "klarna_continue_with_text":"Continue with",
        "trust_rating_popup_headertext": "How would you rate your shopping experience?",
        "trust_rating_popup_subtext":"Your feedback means a lot",
        "trust_rating_buttontext": "Submit",
        "required":"Required Field",
        "invalid_exp_date": "Invalid Expiration Date",
        "error-msg-header":"Payment failed. Please verify your details or use a different payment method.<br/><br/>Reason(s):",
        "wallet-payment-phone-header":"Please fill in the required field(s) below to ensure a smooth and successful delivery of your order.",
        "wallet-payment-submit-text": "Submit",
        "invalid_cpf": "Please enter a valid CPF number.",
        "invalid_houseno": "Please enter house number.",
        "invalid_bairro": "Please enter Bairro.",
        "invalid_neighborhood": "Please enter the neighborhood.",
        "something_wrong":"Something went wrong. ",
        "retry": "Retry",
        "invalid_consigneeId": "Invalid Consignee Id",
        "phone_number" : "Phone Number:",
        "consignee_id" : "Consignee ID:",
        "cpf" : "CPF (Individual Taxpayer Registry):",
        "pccc" : "PCCC (Personal Customs Clearance Code):",
        "invalid_code_id": "Invalid code or ID",
        "paymentMethod_not_return":"PaymentMethod ID was not returned. Please try again later.",
        "invalid_tax_id": "Invalid code or Tax ID",
        'invalid_district': 'Please enter district',
        'invalid_village': 'Please enter village',
        'invalid_apt_unit': 'Please enter apartment/unit number',
        'invalid_county': 'Please enter county',
        'invalid_ward': 'Please enter ward',
        'invalid_address1': 'Please enter address',
        'unable_to_load_suggestions': 'Could not load suggestions',
        'searching': 'Searching...',
        'record_not_found': 'Record not found',
        "invalid_zip_no": "4 digits.",
        "invalid_city_no": "Enter postal code first.",
        "invalid_address_1_no": "Enter street address and number.",
        "invalid_zip_lu": "4 digits.",
        "invalid_city_lu": "Enter the postal code first.",
        "invalid_address_1_lu": "Enter the number and street.",
        "invalid_address_gr": "Enter your street address.",
        "invalid_zip_gr": "5 digits.",
        "invalid_city_gr":"Enter the city."
}