window.i18nData = {
    "invalid_email":"Por favor, introduce una dirección de correo electrónico válida",
    "invalid_fname":"Nombre no válido.",
    "invalid_lname":"Apellido no válido.",
    "invalid_phone":"Número de teléfono no válido.",
    "invalid_cc_month":"Mes de vencimiento de la tarjeta no válido.",
    "invalid_cc_year":"Año de vencimiento de la tarjeta no válido.",
    "invalid_cc":"Número de tarjeta de crédito no válido.",
    "invalid_cvv":"Código de verificación de la tarjeta no válido.",
    "invalid_billing_fname":"Nombre de facturación no válido.",
    "invalid_billing_lname":"Apellido de facturación no válido.",
    "terms_agree":"Por favor, acepta nuestros términos y condiciones.",
    "required_fields":"Los campos obligatorios están resaltados en rojo.",
    "required_fields2":"Por favor, completa los campos obligatorios resaltados en rojo.",
    "no_orders":"No hay pedidos.",
    "decline":"Tu banco está bloqueando este pago. Permanece en este navegador y <b>RESPONDE AL SMS O CORREO ELECTRÓNICO DEL BANCO PARA COMPLETAR ESTE PEDIDO</b>. Verifica tu información e inténtalo de nuevo o utiliza otro método de pago.<br/><br/>Motivo:",
    "no_item_in_cart":"No hay artículos en tu carrito. Por favor, selecciona tu pedido.",
    "page_reload":"La página se recargará después de cerrar el cuadro de diálogo.",
    "invalid_exp_month":"Por favor, introduce un mes válido.",
    "invalid_exp_year":"Por favor, introduce un año válido.",
    "redirect_to_next":"Redirigiendo a la siguiente página.",
    "processing":"Procesando solicitud...",
    "paypal_processing":"Por favor, espera mientras te redirigimos a PayPal Checkout...",
    "loading_msg":"Tu producto está siendo reservado.",
    "loading_msg_header":"Por favor, espera un momento.",
    "select":"Seleccionar",
    "month":"Mes",
    "year":"Año",
    "january":"01 (Ene)",
    "february":"02 (Feb)",
    "march":"03 (Mar)",
    "april":"04 (Abr)",
    "may":"05 (May)",
    "june":"06 (Jun)",
    "july":"07 (Jul)",
    "august":"08 (Ago)",
    "september":"09 (Sep)",
    "october":"10 (Oct)",
    "november":"11 (Nov)",
    "december":"12 (Dic)",
    "klarna_billing_information":"Información de facturación",
    "klarna_email_placeholder":"Correo electrónico preferido",
    "klarna_fname_placeholder":"Nombre",
    "klarna_lname_placeholder":"Apellido",
    "klarna_address1_placeholder":"Dirección",
    "klarna_address2_placeholder":"Apartamento / Suite / Otro",
    "klarna_city_placeholder":"Ciudad",
    "klarna_state_province":"-- Selecciona una provincia --",
    "klarna_postal_code":"Código postal",
    "klarna_continue_with_text":"Continuar con",
    "trust_rating_popup_headertext":"¿Cómo calificarías tu experiencia de compra?",
    "trust_rating_popup_subtext":"Tu opinión es muy importante para nosotros.",
    "trust_rating_buttontext":"Enviar",
    "required":"Campo obligatorio",
    "invalid_exp_date":"Fecha de vencimiento no válida.",
    "error-msg-header":"El pago ha fallado. Verifica tus datos o utiliza otro método de pago.<br/><br/>Motivo(s):",
    "wallet-payment-phone-header":"Por favor, completa los siguientes campos obligatorios para garantizar una entrega correcta y satisfactoria de tu pedido.",
    "wallet-payment-submit-text":"Enviar",
    "invalid_cpf":"Por favor, introduce un número CPF válido.",
    "invalid_houseno":"Por favor, introduce el número de la vivienda.",
    "invalid_bairro":"Por favor, introduce el barrio.",
    "invalid_neighborhood":"Por favor, introduce la colonia.",
    "something_wrong":"Algo salió mal.",
    "retry":"Reintentar",
    "invalid_consigneeId":"ID del destinatario no válido.",
    "phone_number":"Número de teléfono:",
    "consignee_id":"ID del destinatario:",
    "cpf":"CPF (Registro de Personas Físicas):",
    "pccc":"PCCC (Código Personal de Despacho Aduanero):",
    "invalid_code_id":"Código o ID no válido.",
    "paymentMethod_not_return":"No se devolvió el ID del método de pago. Por favor, inténtalo de nuevo más tarde.",
    'invalid_tax_id': "Ingresa un RFC (12–13 caracteres) o CURP (18 caracteres) válido.",
    'invalid_district': 'Introduzca el distrito',
    'invalid_village': 'Introduzca la localidad',
    'invalid_apt_unit': 'Introduzca el número de apartamento/unidad',
    'invalid_county': 'Introduzca la provincia',
    'invalid_ward': 'Introduzca el barrio',
    'invalid_address1': 'Introduzca la dirección',
    'unable_to_load_suggestions': 'No se pudieron cargar las sugerencias',
    'searching': 'Buscando...',
    "record_not_found": "No se ha encontrado el registro",
    "invalid_zip_no": "4 dígitos.",
    "invalid_city_no": "Introduce primero el código postal.",
    "invalid_address_1_no": "Introduce la calle y el número.",
    "invalid_zip_lu": "4 dígitos.",
    "invalid_city_lu": "Introduce primero el código postal.",
    "invalid_address_1_lu": "Introduce el número y la calle.",
    "invalid_address_gr": "Introduce tu dirección.",
    "invalid_zip_gr": "5 dígitos.",
    "invalid_city_gr": "Entra en la ciudad.",
    "invalid_address_rs": "Introduce la calle y el número de la vivienda.",
    "invalid_zip_rs": "5 dígitos.",
    "invalid_city_rs": "Introduce el nombre del pueblo o la ciudad.",
    "invalid_address_ch": "Introduce, por favor, la calle y el número de la vivienda.",
    "invalid_zip_ch": "4 dígitos.",
    "invalid_city_ch": "Introduce una localidad."
};