window.i18nData={
        "invalid_email":"Anna kelvollinen sähköpostiosoite.", 
        "invalid_fname":"Virheellinen etunimi.", 
        "invalid_lname":"Virheellinen sukunimi.", 
        "invalid_phone":"Virheellinen puhelinnumero.", 
        "invalid_cc_month":"Virheellinen kortin vanhentumiskuukausi.", 
        "invalid_cc_year": "Virheellinen kortin vanhentummisvuosi.", 
        "invalid_cc":"Virheellinen luottokortin numero.", 
        "invalid_cvv":"Virheellinen kortin turvakoodi.", 
        "invalid_billing_fname":"Virheellinen laskutusetunimi.", 
        "invalid_billing_lname":"Virheellinen laskutussukunimi.", 
        "terms_agree":"Hyväksy käyttöehdot ja tietosuojakaava.",
        "required_fields":"Vaaditut kentät on korostettu punaisella", 
        "required_fields2" :"Täytä vaaditut kentät, jotka on korostettu punaisella.", 
        "no_orders":"Tilauksia ei ole.",
        "decline": "Pankkisi estää tämän maksun. Säilytä tämä selain avoinna ja <b>VASTAA PANKKISI TEKSTIVIESTIIN TAI SÄHKÖPOSTIIN TILAUKSEN VIIMEISTELEMISEKSI</b>. Tarkista tietosi ja yritä uudelleen tai käytä toista maksutapaa.<br/><br/>Syy:", 
        "no_item_in_cart": "Ostoskorissasi ei ole tuotteita. Valitse tilauksesi.", 
        "page_reload":"Sivu päivittyy valintaikkunan sulkemisen jälkeen.",
        "invalid_exp_month":"Anna kelvollinen kuukausi", 
        "invalid_exp_year":"Anna kelvollinen vuosi.", 
        "redirect_to_next":"Ohjataan seuraavalle sivulle.",
        "processing":"Käsitellään pyyntöä...", 
        "paypal_processing":"Odota, ohjataan sinut PayPal Checkoutiin...", 
        "loading_msg":"Tuotetta varataan",
        "loading_msg_header": "Odota hetki",
        "select": "Valitse", 
        "month" : "Kuukausi", 
        "year" : "Vuosi",
        "january":"01 (Tammi)",
        "february":"02 (Helmi)",
        "march":"03 (Maalis)",
        "april":"04 (Huhti)",
        "may":"05 (Touko)",
        "june":"06 (Kesä)",
        "july":"07 (Heinä)",
        "august":"08 (Elo)",
        "september":"09 (Syys)",
        "october":"10 (Loka)",
        "november":"11 (Marras)",
        "december":"12 (Joulu)",
        "klarna_billing_information": "Laskutustiedot",
        "klarna_email_placeholder":"Ensisijainen sähköpostiosoite",
        "klarna_fname_placeholder":"Etunimi",
        "klarna_lname_placeholder":"Sukunimi",
        "klarna_address1_placeholder":"Katuosoite",
        "klarna_address2_placeholder" :"Asunto / Huoneisto / Muu",
        "klarna_city_placeholder" :"Kaupunki",
        "klarna_state_province" :"-- Valitse maakunta / alue --",
        "klarna_postal_code" :"Postinumero",
        "klarna_continue_with_text":"Jatka",
        "trust_rating_popup_headertext": "Miten arvioisit ostokokemuksesi?",
        "trust_rating_popup_subtext":"Palautteesi on meille tärkeää",
        "trust_rating_buttontext": "Lähetä",
        "required":"Pakollinen kenttä",
        "invalid_exp_date": "Virheellinen vanhentumispäivämäärä",
        "error-msg-header":"Maksu epäonnistui. Tarkista tietosi tai käytä toista maksutapaa.<br/><br/>Syy(t):",
        "wallet-payment-phone-header":"Täytä alla olevat vaaditut kentät tilauksen onnistuneen toimittamisen varmistamiseksi.",
        "wallet-payment-submit-text": "Lähetä",
        "invalid_cpf": "Anna kelvollinen CPF-numero.",
        "invalid_houseno": "Anna talon numero.",
        "invalid_bairro": "Anna Bairro.",
        "invalid_neighborhood": "Anna kaupunginosa.",
        "something_wrong":"Jokin meni pieleen. ",
        "retry": "Yritä uudelleen",
        "invalid_consigneeId": "Virheellinen vastaanottajan tunnus",
        "phone_number" : "Puhelinnumero:",
        "consignee_id" : "Vastaanottajan tunnus:",
        "cpf" : "CPF (henkilön verorekisteri):",
        "pccc" : "PCCC (henkilökohtainen tulli-ilmoituskoodi):",
        "invalid_code_id": "Virheellinen koodi tai tunnus",
        "paymentMethod_not_return":"Maksutapan tunnusta ei palautettu. Yritä myöhemmin uudelleen.",
        "invalid_tax_id": "Virheellinen koodi tai verotunnus",
        'invalid_district': 'Anna piiri',
        'invalid_village': 'Anna kylä',
        'invalid_apt_unit': 'Anna asunnon/yksikön numero',
        'invalid_county': 'Anna maakunta',
        'invalid_ward': 'Anna kaupunginosa',
        'invalid_address1': 'Anna osoite',
        'unable_to_load_suggestions': 'Ehdotuksia ei voitu ladata',
        'searching': 'Haetaan...',
        "record_not_found": "Tietuetta ei löytynyt",
        "invalid_zip_no": "4 numeroa.",
        "invalid_city_no": "Syötä ensin postinumero.",
        "invalid_address_1_no": "Kirjoita kadun nimi ja numero.",
        "invalid_zip_lu": "4 numeroa.",
        "invalid_city_lu": "Syötä ensin postinumero.",
        "invalid_address_1_lu": "Syötä numero ja kadunnimi.",
        "invalid_address_gr": "Kirjoita kadun osoitteesi.",
        "invalid_zip_gr": "5 numeroa.",
        "invalid_city_gr": "Mene kaupunkiin.",
        "invalid_address_rs": "Kirjoita kadunnimi ja talonumero.",
        "invalid_zip_rs": "5 numeroa.",
        "invalid_city_rs": "Kirjoita kaupunki tai paikkakunta.",
        "invalid_address_ch": "Kirjoita katu ja talonumero.",
        "invalid_zip_ch": "4 numeroa.",
        "invalid_city_ch": "Kirjoita kaupunki."
}