window.i18nData = {
    "invalid_email": "Veuillez saisir une adresse e-mail valide.", 
    "invalid_fname": "Prénom invalide.", 
    "invalid_lname": "Nom de famille invalide.", 
    "invalid_phone": "Numéro de téléphone invalide.", 
    "invalid_cc_month": "Mois d'expiration de la carte invalide.", 
    "invalid_cc_year": "Année d'expiration de la carte invalide.", 
    "invalid_cc": "Numéro de carte de crédit invalide.", 
    "invalid_cvv": "Code de vérification de la carte invalide.", 
    "invalid_billing_fname": "Prénom de facturation invalide.", 
    "invalid_billing_lname": "Nom de famille de facturation invalide.", 
    "terms_agree": "Veuillez accepter nos conditions générales.", 
    "required_fields": "Champ(s) obligatoire(s) surligné(s) en rouge", 
    "required_fields2": "Veuillez remplir les champs obligatoires surlignés en rouge.", 
    "no_orders": "Il n'y a aucune commande.", 
    "decline": "Votre banque bloque ce paiement. Veuillez rester sur ce navigateur et <b>RÉPONDRE AU SMS OU À L'E-MAIL DE LA BANQUE POUR FINALISER CETTE COMMANDE</b>. Veuillez vérifier vos informations et réessayer ou utiliser un autre moyen de paiement.<br/><br/>Raison :", 
    "no_item_in_cart": "Il n'y a aucun article dans votre panier. Veuillez sélectionner votre commande.", 
    "page_reload": "La page se rechargera après la fermeture de la boîte de dialogue.", 
    "invalid_exp_month": "Veuillez entrer un mois valide.", 
    "invalid_exp_year": "Veuillez entrer une année valide.", 
    "redirect_to_next": "Redirection vers la page suivante.", 
    "processing": "Traitement en cours...", 
    "paypal_processing": "Veuillez patienter pendant que nous vous redirigeons vers le paiement PayPal...", 
    "loading_msg": "Votre produit est en cours de réservation", 
    "loading_msg_header": "Veuillez patienter un instant", 
    "select": "Sélectionner", 
    "month": "Mois", 
    "year": "Année",
    "january": "01 (Janv)", 
    "february": "02 (Févr)", 
    "march": "03 (Mars)", 
    "april": "04 (Avr)", 
    "may": "05 (Mai)", 
    "june": "06 (Juin)", 
    "july": "07 (Juil)", 
    "august": "08 (Août)", 
    "september": "09 (Sept)", 
    "october": "10 (Oct)", 
    "november": "11 (Nov)", 
    "december": "12 (Déc)", 
    "klarna_billing_information": "Informations de facturation", 
    "klarna_email_placeholder": "Adresse e-mail préférée", 
    "klarna_fname_placeholder": "Prénom", 
    "klarna_lname_placeholder": "Nom de famille", 
    "klarna_address1_placeholder": "Adresse", 
    "klarna_address2_placeholder": "Appartement / Suite / Autre", 
    "klarna_city_placeholder": "Ville", 
    "klarna_state_province": "-- Sélectionnez l'État / Province --", 
    "klarna_postal_code": "Code postal", 
    "klarna_continue_with_text": "Continuer avec", 
    "trust_rating_popup_headertext": "Comment évalueriez-vous votre expérience d'achat ?", 
    "trust_rating_popup_subtext": "Votre avis est très important pour nous", 
    "trust_rating_buttontext": "Soumettre", 
    "required": "Champ obligatoire", 
    "invalid_exp_date": "Date d'expiration invalide", 
    "error-msg-header": "Le paiement a échoué. Veuillez vérifier vos informations ou utiliser un autre moyen de paiement.<br/><br/>Raison(s) :", 
    "wallet-payment-phone-header": "Veuillez remplir les champs obligatoires ci-dessous afin de garantir une livraison rapide et sans encombre de votre commande.", 
    "wallet-payment-submit-text": "Soumettre", 
    "invalid_cpf": "Veuillez entrer un numéro CPF valide.", 
    "invalid_houseno": "Veuillez entrer le numéro de maison.", 
    "invalid_bairro": "Veuillez entrer le quartier (Bairro).",
    "invalid_neighborhood": "Veuillez entrer le quartier.",
    "something_wrong": "Une erreur s'est produite.", 
    "retry": "Réessayer", 
    "invalid_consigneeId": "Identifiant du destinataire invalide",
    "phone_number" : "Numéro de téléphone:",
    "consignee_id" : "Identifiant du destinataire:",
    "cpf" : "CPF (Registre des contribuables):",
    "pccc" : "PCCC (code de dédouanement personnel) :",
    "invalid_code_id": "Code ou identifiant incorrect",
    "paymentMethod_not_return":"L'identifiant de la méthode de paiement n'a pas été renvoyé. Veuillez réessayer plus tard. ",
    "invalid_tax_id": "Code ou numéro fiscal invalide",
    'invalid_district': 'Veuillez saisir le district',
    'invalid_village': 'Veuillez saisir le village',
    'invalid_apt_unit': 'Veuillez saisir le numéro de l’appartement/unité',
    'invalid_county': 'Veuillez saisir le comté',
    'invalid_ward': 'Veuillez saisir le quartier',
    'invalid_address1': 'Veuillez saisir l’adresse',
    'unable_to_load_suggestions': 'Impossible de charger les suggestions',
    'searching': 'Recherche en cours...',
    "record_not_found": "Enregistrement introuvable",
    "invalid_zip_no": "4 chiffres.",
    "invalid_city_no": "Entrez d'abord le code postal.",
    "invalid_address_1_no": "Saisissez le nom de la rue et le numéro.",
    "invalid_zip_lu": "4 chiffres.",
    "invalid_city_lu": "Commencez par saisir le code postal.",
    "invalid_address_1_lu": "Indiquez le numéro et le nom de la rue.",
    "invalid_address_gr": "Saisissez votre adresse postale.",
    "invalid_zip_gr": "5 chiffres.",
    "invalid_city_gr": "Entrez dans la ville.",
    "invalid_address_rs": "Indiquez le nom de la rue et le numéro de la maison.",
    "invalid_zip_rs": "5 chiffres.",
    "invalid_city_rs": "Indiquez le nom de la ville."
};