window.i18nData = {
    "invalid_email": "Kérjük, adjon meg egy érvényes e-mail-címet.", 
    "invalid_fname": "Érvénytelen keresztnév.", 
    "invalid_lname": "Érvénytelen vezetéknév.", 
    "invalid_phone": "Érvénytelen telefonszám.", 
    "invalid_cc_month": "Érvénytelen kártya lejáratának hónapja.", 
    "invalid_cc_year": "Érvénytelen kártya lejáratának éve.", 
    "invalid_cc": "Érvénytelen hitelkártyaszám.", 
    "invalid_cvv": "Érvénytelen kártyaellenőrzési kód.", 
    "invalid_billing_fname": "Érvénytelen számlázási keresztnév.", 
    "invalid_billing_lname": "Érvénytelen számlázási vezetéknév.", 
    "terms_agree": "Kérjük, fogadja el az általános szerződési feltételeket.", 
    "required_fields": "Kötelező mező(k) piros szín kiemelve", 
    "required_fields2": "Kérjük, töltse ki a kötelező mezőket, amelyek piros színnel vannak kiemelve.", 
    "no_orders": "Nincs rendelés.", 
    "decline": "A bank blokkolja ezt a fizetést. Kérjük, maradjon ezen a böngészőn és <b>VÁLASZOLJON A BANK SMS-ÉRE VAGY E-MAILJÉRE ENNEK A MEGRENDELÉSNEK A BEFEJEZÉSÉHEZ</b>. Kérjük, ellenőrizze adatait és próbálja újra, vagy használjon másik fizetési módot.<br/><br/>Ok :", 
    "no_item_in_cart": "Nincs elem a kosarában. Kérjük, válassza ki a megrendelést.", 
    "page_reload": "Az oldal újratöltődik a párbeszédablak bezárása után.", 
    "invalid_exp_month": "Kérjük, adjon meg egy érvényes hónapot.", 
    "invalid_exp_year": "Kérjük, adjon meg egy érvényes évet.", 
    "redirect_to_next": "Átirányítás a következő oldalra.", 
    "processing": "Feldolgozás folyamatban...", 
    "paypal_processing": "Kérjük, várjon, miközben átirányítjuk a PayPal fizetéshez...", 
    "loading_msg": "Terméke foglalás alatt van", 
    "loading_msg_header": "Kérjük, egy pillanatig várjon", 
    "select": "Válasszon megyét", 
    "month": "Hó", 
    "year": "Év",
    "january": "01 (Jan)", 
    "february": "02 (Feb)", 
    "march": "03 (Márc)", 
    "april": "04 (Ápr)", 
    "may": "05 (Máj)", 
    "june": "06 (Jún)", 
    "july": "07 (Júl)", 
    "august": "08 (Aug)", 
    "september": "09 (Sze)", 
    "october": "10 (Okt)", 
    "november": "11 (Nov)", 
    "december": "12 (Dec)", 
    "klarna_billing_information": "Számlázási információk", 
    "klarna_email_placeholder": "Előnyben részesített e-mail cím", 
    "klarna_fname_placeholder": "Keresztnév", 
    "klarna_lname_placeholder": "Vezetéknév", 
    "klarna_address1_placeholder": "Cím", 
    "klarna_address2_placeholder": "Apartman / Csomag / Egyéb", 
    "klarna_city_placeholder": "Város", 
    "klarna_state_province": "-- Válasszon államot / tartományt --", 
    "klarna_postal_code": "Irányítószám", 
    "klarna_continue_with_text": "Folytatás vele", 
    "trust_rating_popup_headertext": "Hogyan értékelné a vásárlási élményt?", 
    "trust_rating_popup_subtext": "Az Ön véleménye nagyon fontos számunkra", 
    "trust_rating_buttontext": "Beküldés", 
    "required": "Kötelező mező", 
    "invalid_exp_date": "Érvénytelen lejárati dátum", 
    "error-msg-header": "A fizetés sikertelen. Kérjük, ellenőrizze adatait vagy használjon másik fizetési módot.<br/><br/>Ok(ok) :", 
    "wallet-payment-phone-header": "Kérjük, töltse ki az alábbi kötelező mezőket, hogy biztosítsa megrendelésének gyors és zökkenőmentes kézbesítését.", 
    "wallet-payment-submit-text": "Beküldés", 
    "invalid_cpf": "Kérjük, adjon meg egy érvényes CPF-számot.", 
    "invalid_houseno": "Kérjük, adja meg a házszámot.", 
    "invalid_bairro": "Kérjük, adja meg a kerületet (Bairro).",
    "invalid_neighborhood": "Kérjük, adja meg a kerületet.",
    "something_wrong": "Hiba lépett fel.", 
    "retry": "Újra", 
    "invalid_consigneeId": "Érvénytelen címzett azonosító",
    "phone_number" : "Telefonszám:",
    "consignee_id" : "Címzett azonosító:",
    "cpf" : "CPF (Adófizető nyilvántartás):",
    "pccc" : "PCCC (személyes vámkódkód) :",
    "invalid_code_id": "Érvénytelen kód vagy azonosító",
    "paymentMethod_not_return":"A fizetési módszer azonosítóját nem adták vissza. Kérjük, később próbálja újra. ",
    "invalid_tax_id": "Érvénytelen kód vagy adóazonosító jel",
    'invalid_district': 'Kérjük, adja meg a kerületet',
    'invalid_village': 'Kérjük, adja meg a települést',
    'invalid_apt_unit': 'Kérjük, adja meg a lakás/egység számát',
    'invalid_county': 'Kérjük, adja meg a megyét',
    'invalid_ward': 'Kérjük, adja meg a városrészt',
    'invalid_address1': 'Kérjük, adja meg a címet',
    'unable_to_load_suggestions': 'Nem sikerült betölteni a javaslatokat',
    'searching': 'Keresés...',
    "record_not_found": "A rekord nem található",
    "invalid_zip_no": "4 számjegy.",
    "invalid_city_no": "Először írja be az irányítószámot.",
    "invalid_address_1_no": "Írja be az utca nevét és a házszámot.",
    "invalid_zip_lu": "4 számjegy.",
    "invalid_city_lu": "Először írja be az irányítószámot.",
    "invalid_address_1_lu": "Írja be a házszámot és az utcanevet.",
    "invalid_address_gr": "Írja be a lakcímét.",
    "invalid_zip_gr": "5 számjegy.",
    "invalid_city_gr": "Lépj be a városba!",
    "invalid_address_rs": "Írja be az utcanevet és a házszámot.",
    "invalid_zip_rs": "5 számjegy.",
    "invalid_city_rs": "Írja be a település nevét.",
    "invalid_address_ch": "Kérjük, adja meg az utcanevet és a házszámot.",
    "invalid_zip_ch": "4 számjegy.",
    "invalid_city_ch": "Kérjük, adja meg a város nevét."
};