window.i18nData={
        "invalid_email":"Silakan masukkan alamat email yang valid",
        "invalid_fname":"Nama Depan Tidak Valid.",
        "invalid_lname":"Nama Belakang Tidak Sah.",
        "invalid_phone":"Nomor Telepon Tidak Sah.",
        "invalid_cc_month":"Bulan Kedaluwarsa Kartu Tidak Sah.",
        "invalid_cc_year": "Tahun Kedaluwarsa Kartu Tidak Valid.",
        "invalid_cc":"Nomor Kartu Kredit Tidak Sah.",
        "invalid_cvv":"Nilai Verifikasi Kartu Tidak Sah.",
        "invalid_billing_fname":"Nama Depan pada Tagihan Tidak Sah.",
        "invalid_billing_lname":"Nama Belakang pada Tagihan Tidak Valid.",
        "terms_agree":"Mohon setujui syarat dan ketentuan kami.",
        "required_fields":"Kolom yang wajib diisi ditandai dengan warna merah",
        "required_fields2" :"Silakan isi kolom-kolom yang wajib diisi dan ditandai dengan warna merah.",
        "no_orders":"Tidak ada pesanan.",
        "decline": "Bank Anda memblokir pembayaran ini. Harap tetap menggunakan browser ini dan <b>MENJAWAB SMS ATAU EMAIL DARI BANK UNTUK MENYELESAIKAN PESANAN INI</b>. Harap periksa kembali informasi Anda dan coba lagi, atau gunakan metode pembayaran lain.<br/><br/>Alasan:",
        "no_item_in_cart": "Tidak ada barang di keranjang belanja Anda. Silakan pilih pesanan Anda.",
        "page_reload":"Halaman ini akan dimuat ulang setelah Anda menutup kotak dialog tersebut.",
        "invalid_exp_month":"Silakan masukkan bulan yang valid",
        "invalid_exp_year":"Silakan masukkan tahun yang valid.",
        "redirect_to_next":"Sedang dialihkan ke halaman berikutnya.",
        "processing":"Memproses permintaan...",
        "paypal_processing":"Mohon tunggu sebentar, kami akan mengalihkan Anda ke halaman pembayaran PayPal...",
        "loading_msg":"Produk Anda Sedang Dipesankan",
        "loading_msg_header": "Mohon tunggu sebentar",
        "select": "Pilih",
        "month" : "Bulan",
        "year" : "Tahun",
        "january":"01 (Jan)",
        "february":"02 (Feb)",
        "march":"03 (Mar)",
        "april":"04 (Apr)",
        "may":"05 (Mei)",
        "june":"06 (Jun)",
        "july":"07 (Jul)",
        "august":"08 (Agu)",
        "september":"09 (Sep)",
        "october":"10 (Okt)",
        "november":"11 (Nov)",
        "december":"12 (Des)",
        "klarna_billing_information": "Informasi Penagihan",
        "klarna_email_placeholder":"Alamat Email Pilihan",
        "klarna_fname_placeholder":"Nama Depan",
        "klarna_lname_placeholder":"Nama Keluarga",
        "klarna_address1_placeholder":"Alamat Jalan",
        "klarna_address2_placeholder" :"Apartemen / Suite / Lainnya",
        "klarna_city_placeholder" :"Kota",
        "klarna_state_province" :"-- Pilih Negara Bagian / Provinsi --",
        "klarna_postal_code" :"Kode Pos",
        "klarna_continue_with_text":"Lanjutkan ke",
        "trust_rating_popup_headertext": "Bagaimana Anda menilai pengalaman berbelanja Anda?",
        "trust_rating_popup_subtext":"Masukan Anda sangat berarti bagi kami",
        "trust_rating_buttontext": "Kirim",
        "required":"Kolom Wajib Diisi",
        "invalid_exp_date": "Tanggal Kedaluwarsa Tidak Sah",
        "error-msg-header":"Pembayaran gagal. Silakan periksa kembali detail Anda atau gunakan metode pembayaran lain.<br/><br/>Alasan:",
        "wallet-payment-phone-header":"Silakan isi kolom-kolom yang wajib diisi di bawah ini agar pengiriman pesanan Anda berjalan lancar dan berhasil.",
        "wallet-payment-submit-text": "Kirim",
        "invalid_cpf": "Silakan masukkan nomor CPF yang sah.",
        "invalid_houseno": "Silakan masukkan nomor rumah.",
        "invalid_bairro": "Silakan masukkan Bairro.",
        "invalid_neighborhood": "Silakan masukkan lingkungan.",
        "something_wrong":"Terjadi kesalahan. ",
        "retry": "Coba Lagi",
        "invalid_consigneeId": "ID Penerima Barang Tidak Sah",
        "phone_number" : "Nomor Telepon:",
        "consignee_id" : "ID Penerima Barang:",
        "cpf" : "CPF (Daftar Wajib Pajak Perorangan):",
        "pccc" : "PCCC (Kode Klarifikasi Bea Cukai Pribadi):",
        "invalid_code_id": "Kode atau ID tidak valid",
        "paymentMethod_not_return":"ID Metode Pembayaran tidak dikembalikan. Silakan coba lagi nanti.",
        "invalid_tax_id": "Kode atau ID Pajak tidak valid",
        'invalid_district': 'Silakan masukkan distrik',
        'invalid_village': 'Silakan masukkan desa',
        'invalid_apt_unit': 'Silakan masukkan nomor apartemen/unit',
        'invalid_county': 'Silakan masukkan kabupaten',
        'invalid_ward': 'Silakan masukkan kelurahan',
        'invalid_address1': 'Silakan masukkan alamat',
        'unable_to_load_suggestions': 'Tidak dapat memuat saran',
        'searching': 'Mencari...',
        "record_not_found": "Catatan tidak ditemukan",
        "invalid_zip_no": "4 digit.",
        "invalid_city_no": "Masukkan kode pos terlebih dahulu.",
        "invalid_address_1_no": "Masukkan alamat jalan dan nomor rumah.",
        "invalid_zip_lu": "4 digit.",
        "invalid_city_lu": "Masukkan kode pos terlebih dahulu.",
        "invalid_address_1_lu": "Masukkan nomor dan nama jalan.",
        "invalid_address_gr": "Masukkan alamat jalan Anda.",
        "invalid_zip_gr": "5 digit.",
        "invalid_city_gr": "Masuklah ke kota."
}
