window.i18nData={
        "invalid_email":"Inserisci un indirizzo e-mail valido.",
        "invalid_fname":"Nome non valido.",
        "invalid_lname":"Cognome non valido.",
        "invalid_phone":"Numero di telefono non valido.",
        "invalid_cc_month":"Mese di scadenza della carta non valido.",
        "invalid_cc_year": "Anno di scadenza della carta non valido.",
        "invalid_cc":"Numero di carta di credito non valido.",
        "invalid_cvv":"Codice di verifica della carta non valido.",
        "invalid_billing_fname":"Nome di fatturazione non valido.",
        "invalid_billing_lname":"Cognome di fatturazione non valido.",
        "terms_agree":"Si prega di accettare i nostri termini e condizioni.",
        "required_fields":"Campo/i obbligatorio/i evidenziato/i in rosso",
        "required_fields2":"Si prega di compilare i campi obbligatori evidenziati in rosso.",
        "no_orders":"Non ci sono ordini.",
        "decline": "La tua banca sta bloccando questo pagamento. Rimani su questo browser e <b>RISPONDI ALL'SMS O ALL'EMAIL DELLA BANCA PER COMPLETARE QUESTO ORDINE</b>. Verifica le tue informazioni e riprova oppure utilizza un metodo di pagamento diverso.<br/><br/>Motivo:",
        "no_item_in_cart": "Non ci sono articoli nel tuo carrello. Seleziona il tuo ordine.",
        "page_reload":"La pagina verrà ricaricata dopo la chiusura della finestra di dialogo.",
        "invalid_exp_month":"Inserisci un mese valido.",
        "invalid_exp_year":"Inserisci un anno valido.",
        "redirect_to_next":"Reindirizzamento alla pagina successiva.",
        "processing":"Elaborazione della richiesta in corso...",
        "paypal_processing":"Attendere mentre ti reindirizziamo al pagamento PayPal...",
        "loading_msg":"Il tuo prodotto è in fase di prenotazione",
        "loading_msg_header": "Attendi un momento",
        "select": "Seleziona provincia",
        "month" : "Mese",
        "year" : "Anno",
        "january":"01 (Gen)",
        "february":"02 (Feb)",
        "march":"03 (Mar)",
        "april":"04 (Apr)",
        "may":"05 (Mag)",
        "june":"06 (Giu)",
        "july":"07 (Lug)",
        "august":"08 (Ago)",
        "september":"09 (Set)",
        "october":"10 (Ott)",
        "november":"11 (Nov)",
        "december":"12 (Dic)",
        "klarna_billing_information": "Informazioni di fatturazione",
        "klarna_email_placeholder":"Indirizzo email preferito",
        "klarna_fname_placeholder":"Nome",
        "klarna_lname_placeholder":"Cognome",
        "klarna_address1_placeholder":"Indirizzo",
        "klarna_address2_placeholder":"App. / Suite / Altro",
        "klarna_city_placeholder":"Città",
        "klarna_state_province":"-- Seleziona Stato / Provincia --",
        "klarna_postal_code":"CAP / Codice Postale",
        "klarna_continue_with_text":"Continua con",
        "trust_rating_popup_headertext": "Come valuteresti la tua esperienza di acquisto?",
        "trust_rating_popup_subtext":"Il tuo feedback è molto importante per noi",
        "trust_rating_buttontext": "Invia",
        "required":"Campo obbligatorio",
        "invalid_exp_date": "Data di scadenza non valida",
        "error-msg-header":"Pagamento non riuscito. Verifica i tuoi dati oppure utilizza un metodo di pagamento diverso.<br/><br/>Motivo/i:",
        "wallet-payment-phone-header":"Compila i campi obbligatori qui sotto per garantire una consegna corretta e puntuale del tuo ordine.",
        "wallet-payment-submit-text": "Invia",
        "invalid_cpf": "Inserisci un numero CPF valido.",
        "invalid_houseno": "Inserisci il numero civico.",
        "invalid_bairro": "Inserisci il Bairro.",
        "invalid_neighborhood": "Inserisci il quartiere.",
        "something_wrong":"Qualcosa è andato storto. ",
        "retry": "Riprova",
        "invalid_consigneeId": "ID destinatario non valido",
        "phone_number" : "Numero di telefono:",
        "consignee_id" : "ID destinatario:",
        "cpf" : "CPF (Registro dei Contribuenti Individuali):",
        "pccc" : "PCCC (Codice Personale di Sdoganamento):",
        "invalid_code_id": "Codice o ID non valido",
        "paymentMethod_not_return":"L'ID del metodo di pagamento non è stato restituito. Riprova più tardi.",
        "invalid_tax_id": "Codice o codice fiscale non valido",
        'invalid_district': 'Inserisci il distretto',
        'invalid_village': 'Inserisci il villaggio',
        'invalid_apt_unit': 'Inserisci il numero dell’appartamento/unità',
        'invalid_county': 'Inserisci la contea',
        'invalid_ward': 'Inserisci il quartiere',
        'invalid_address1': 'Inserisci l’indirizzo',
        'unable_to_load_suggestions': 'Impossibile caricare i suggerimenti',
        'searching': 'Ricerca in corso...',
        "record_not_found": "Record non trovato",
        "invalid_zip_no": "4 cifre.",
        "invalid_city_no": "Inserisci prima il codice postale.",
        "invalid_address_1_no": "Inserisci via e numero civico.",
        "invalid_zip_lu": "4 cifre.",
        "invalid_city_lu": "Inserisci prima il codice postale.",
        "invalid_address_1_lu": "Inserisci il numero civico e il nome della via.",
        "invalid_address_gr": "Inserisci il tuo indirizzo.",
        "invalid_zip_gr": "5 cifre.",
        "invalid_city_gr": "Entra in città."
}