window.i18nData={
        "invalid_email":"有効なメールアドレスを入力してください", 
        "invalid_fname":"無効なファーストネームです。", 
        "invalid_lname":"無効な姓です。", 
        "invalid_phone":"無効な電話番号です。", 
        "invalid_cc_month":"カード有効期限月が不正です。", 
        "invalid_cc_year": "カード有効期限の年が不正です。", 
        "invalid_cc":"無効なクレジットカード番号です。", 
        "invalid_cvv":"カード検証値が無効です。", 
        "invalid_billing_fname":"請求先名（ファーストネーム）が無効です。", 
        "invalid_billing_lname":"請求先姓が無効です。", 
        "terms_agree":"当社の利用規約に同意してください。",
        "required_fields":"必須項目は赤色で強調表示されています", 
        "required_fields2" :"赤色で強調表示されている必須項目をすべて入力してください。", 
        "no_orders":"注文はありません。",
        "decline": "お取引先の銀行がこの支払いをブロックしています。このブラウザを閉じずに、<b>銀行からのSMSまたはメールに返信して注文を完了してください</b>。情報を確認の上、再度お試しいただくか、別の支払い方法をご利用ください。<br/><br/>理由：", 
        "no_item_in_cart": "カートに商品が入っていません。ご注文品をお選びください。", 
        "page_reload":"ダイアログを閉じると、ページが再読み込みされます。",
        "invalid_exp_month":"有効な月を入力してください", 
        "invalid_exp_year":"有効な年を入力してください。", 
        "redirect_to_next":"まもなく次のページへ移動します。",
        "processing":"リクエストを処理中...", 
        "paypal_processing":"PayPalチェックアウトへリダイレクト中です。お待ちください...", 
        "loading_msg":"商品が予約中です",
        "loading_msg_header": "少々お待ちください",
        "select": "選択", 
        "month" : "月", 
        "year" : "年",
        "january":"01 (1月)",
        "february":"02 (2月)",
        "march":"03 (3月)",
        "april":"04 (4月)",
        "may":"05 (5月)",
        "june":"06 (6月)",
        "july":"07 (7月)",
        "august":"08 (8月)",
        "september":"09 (9月)",
        "october":"10 (10月)",
        "november":"11 (11月)",
        "december":"12 (12月)",
        "klarna_billing_information": "請求情報",
        "klarna_email_placeholder":"優先メールアドレス",
        "klarna_fname_placeholder":"ファーストネーム",
        "klarna_lname_placeholder":"姓",
        "klarna_address1_placeholder":"住所",
        "klarna_address2_placeholder" :"アパート / スイート / その他",
        "klarna_city_placeholder" :"都市",
        "klarna_state_province" :"州／都道府県を選択",
        "klarna_postal_code" :"郵便番号",
        "klarna_continue_with_text":"続けてください",
        "trust_rating_popup_headertext": "ショッピング体験をどのように評価しますか？",
        "trust_rating_popup_subtext":"ご意見・ご感想は大変貴重です",
        "trust_rating_buttontext": "送信",
        "required":"必須項目",
        "invalid_exp_date": "無効な有効期限",
        "error-msg-header":"お支払いが失敗しました。詳細を確認するか、別の支払い方法をご利用ください。<br/><br/>理由：",
        "wallet-payment-phone-header":"ご注文を確実かつスムーズに配送するため、以下の必須項目にご記入ください。",
        "wallet-payment-submit-text": "送信",
        "invalid_cpf": "有効なCPF番号を入力してください。",
        "invalid_houseno": "番地を入力してください。",
        "invalid_bairro": "バイロを入力してください。",
        "invalid_neighborhood": "地区を入力してください。",
        "something_wrong":"何か問題が発生しました。",
        "retry": "再試行",
        "invalid_consigneeId": "受取人IDが無効です",
        "phone_number" : "電話番号:",
        "consignee_id" : "荷受人ID:",
        "cpf" : "CPF（個人納税者登録制度）:",
        "pccc" : "PCCC（個人通関コード）：",
        "invalid_code_id": "コードまたはIDが無効です",
        "paymentMethod_not_return":"支払い方法IDが返されませんでした。後ほど再度お試しください。",
        "invalid_tax_id": "無効なコードまたは納税者番号",
        'invalid_district': '地区を入力してください',
        'invalid_village': '村を入力してください',
        'invalid_apt_unit': 'アパート・ユニット番号を入力してください',
        'invalid_county': '郡を入力してください',
        'invalid_ward': '区を入力してください',
        'invalid_address1': '住所を入力してください',
        'unable_to_load_suggestions': '候補を読み込めませんでした',
        'searching': '検索中...',
        "record_not_found": "記録が見つかりません",
        "invalid_zip_no": "4桁。",
        "invalid_city_no": "まず郵便番号を入力してください。",
        "invalid_address_1_no": "通り名と番地を入力してください。",
        "invalid_zip_lu": "4桁。",
        "invalid_city_lu": "まず郵便番号を入力してください。",
        "invalid_address_1_lu": "番地と通り名を入力してください。",
        "invalid_address_gr": "住所を入力してください。",
        "invalid_zip_gr": "5桁。",
        "invalid_city_gr": "街へ入る。"
}