window.i18nData = {
    "invalid_email": "유효한 이메일 주소를 입력해 주세요.", 
    "invalid_fname": "유효하지 않은 이름입니다.", 
    "invalid_lname": "유효하지 않은 성입니다.", 
    "invalid_phone": "유효하지 않은 전화번호입니다.", 
    "invalid_cc_month": "유효하지 않은 카드 만료 월입니다.", 
    "invalid_cc_year": "유효하지 않은 카드 만료 연도입니다.", 
    "invalid_cc": "유효하지 않은 신용카드 번호입니다.", 
    "invalid_cvv": "유효하지 않은 카드 보안 코드입니다.", 
    "invalid_billing_fname": "유효하지 않은 청구 이름입니다.", 
    "invalid_billing_lname": "유효하지 않은 청구 성입니다.", 
    "terms_agree": "이용 약관에 동의해 주세요.",
    "required_fields": "필수 입력 항목이 빨간색으로 표시되어 있습니다.", 
    "required_fields2": "빨간색으로 표시된 필수 항목을 입력해 주세요.", 
    "no_orders": "주문이 없습니다.",
    "decline": "은행에서 이 결제를 차단했습니다. 이 브라우저를 유지한 상태에서 <b>주문을 완료하려면 은행에서 보낸 SMS 또는 이메일에 응답하세요</b>. 정보를 확인 후 다시 시도하거나 다른 결제 방법을 사용하세요.<br/><br/>사유:", 
    "no_item_in_cart": "장바구니에 상품이 없습니다. 주문할 상품을 선택해 주세요.", 
    "page_reload": "대화 상자를 닫으면 페이지가 새로고침됩니다.",
    "invalid_exp_month": "유효한 월을 입력해 주세요.", 
    "invalid_exp_year": "유효한 연도를 입력해 주세요.", 
    "redirect_to_next": "다음 페이지로 이동 중입니다.",
    "processing": "요청을 처리 중입니다...", 
    "paypal_processing": "PayPal 결제로 이동 중입니다. 잠시만 기다려 주세요...", 
    "loading_msg": "상품을 예약 중입니다",
    "loading_msg_header": "잠시만 기다려 주세요",
    "select": "선택", 
    "month": "월", 
    "year": "연도",
    "january": "01 (1월)",
    "february": "02 (2월)",
    "march": "03 (3월)",
    "april": "04 (4월)",
    "may": "05 (5월)",
    "june": "06 (6월)",
    "july": "07 (7월)",
    "august": "08 (8월)",
    "september": "09 (9월)",
    "october": "10 (10월)",
    "november": "11 (11월)",
    "december": "12 (12월)",
    "klarna_billing_information": "청구 정보",
    "klarna_email_placeholder": "이메일 주소",
    "klarna_fname_placeholder": "이름",
    "klarna_lname_placeholder": "성",
    "klarna_address1_placeholder": "주소",
    "klarna_address2_placeholder": "아파트 / 호수 / 기타",
    "klarna_city_placeholder": "도시",
    "klarna_state_province": "-- 주 / 도 선택 --",
    "klarna_postal_code": "우편번호",
    "klarna_continue_with_text": "다음으로 계속",
    "trust_rating_popup_headertext": "쇼핑 경험을 어떻게 평가하시겠습니까?",
    "trust_rating_popup_subtext": "귀하의 의견은 매우 소중합니다",
    "trust_rating_buttontext": "제출",
    "required": "필수 입력 항목",
    "invalid_exp_date": "유효하지 않은 만료일입니다",
    "error-msg-header": "결제에 실패했습니다. 정보를 확인하거나 다른 결제 방법을 사용해 주세요.<br/><br/>사유:",
    "wallet-payment-phone-header": "원활한 배송을 위해 아래 필수 정보를 입력해 주세요.",
    "wallet-payment-submit-text": "제출",
    "invalid_cpf": "유효한 CPF 번호를 입력해 주세요.",
    "invalid_houseno": "집 번호를 입력해 주세요.",
    "invalid_bairro": "Bairro를 입력해 주세요.",
    "invalid_neighborhood": "동네를 입력해 주세요.",
    "something_wrong": "문제가 발생했습니다. ",
    "retry": "다시 시도",
    "invalid_consigneeId": "유효하지 않은 수취인 ID입니다.",
    "phone_number": "전화번호:",
    "consignee_id": "수취인 ID:",
    "cpf": "CPF (개인 납세자 등록번호):",
    "pccc" : "PCCC(개인 통관 코드):",
    "invalid_code_id": "잘못된 코드 또는 ID",
    "paymentMethod_not_return":"결제 수단 ID가 반환되지 않았습니다. 잠시 후 다시 시도해 주세요.",
    "invalid_tax_id": "유효하지 않은 코드 또는 세금 ID",
    'invalid_district': '구역을 입력해 주세요',
    'invalid_village': '마을을 입력해 주세요',
    'invalid_apt_unit': '아파트/호수 번호를 입력해 주세요',
    'invalid_county': '군을 입력해 주세요',
    'invalid_ward': '동을 입력해 주세요',
    'invalid_address1': '주소를 입력해 주세요',
    'unable_to_load_suggestions': '추천 항목을 불러올 수 없습니다',
    'searching': '검색 중...',
    "record_not_found": "해당 기록을 찾을 수 없습니다.",
    "invalid_zip_no": "4자리.",
    "invalid_city_no": "먼저 우편번호를 입력하세요.",
    "invalid_address_1_no": "도로명과 번호를 입력하세요.",
    "invalid_zip_lu": "4자리.",
    "invalid_city_lu": "먼저 우편번호를 입력하세요.",
    "invalid_address_1_lu": "번호와 도로명을 입력하세요.",
    "invalid_address_gr": "주소를 입력해 주세요.",
    "invalid_zip_gr": "5자리.",
    "invalid_city_gr": "도시로 들어가세요."
};