window.i18nData={
        "invalid_email":"W.e.g. gitt eng gülteg E-Mail-Adress an",
        "invalid_fname":"Ongültegen Virnumm.",
        "invalid_lname":"Ongültegen Familljennumm.",
        "invalid_phone":"Ongülteg Telefonsnummer.",
        "invalid_cc_month":"Ongültege Kaart-Verfallsmonat.",
        "invalid_cc_year": "Ongültegt Kaart-Verfallsjoer.",
        "invalid_cc":"Ongülteg Kreditkaardnummer.",
        "invalid_cvv":"Ongültege Kaart-Verifikatiounswäert.",
        "invalid_billing_fname":"Ongültegen Rechnungs-Virnumm.",
        "invalid_billing_lname":"Ongültegen Rechnungs-Familljennumm.",
        "terms_agree":"W.e.g. akzeptéiert eis Notzungsbedéngungen.",
        "required_fields":"Obligatoresch Felder si rout markéiert",
        "required_fields2" :"W.e.g. fëllt déi rout markéiert Pflichtfelder aus.",
        "no_orders":"Et ginn keng Bestellungen.",
        "decline": "Är Bank blockéiert dës Bezuelung. W.e.g. bleift op dësem Browser a <b>REAGÉIERT AUF DEN BANK-SMS ODER D'E-MAIL FIR DËS BESTELLUNG OFZESCHLÉISSEN</b>. W.e.g. iwwerpréift Är Informatiounen a probéiert nach eng Kéier oder benotzt eng aner Bezuelmethod.<br/><br/>Grond:",
        "no_item_in_cart": "Et ginn keng Artikelen an Ärem Warenkorb. W.e.g. wielt Är Bestellung.",
        "page_reload":"D'Säit gëtt nei gelueden nodeems Dir den Dialog zoumaacht.",
        "invalid_exp_month":"W.e.g. gitt e gültege Monat an",
        "invalid_exp_year":"W.e.g. gitt e gültegt Joer an.",
        "redirect_to_next":"Dir gitt op déi nächst Säit weidergeleitet.",
        "processing":"Ufro gëtt veraarbecht...",
        "paypal_processing":"W.e.g. waart wärend mir iech zu PayPal Checkout weiderleeën...",
        "loading_msg":"Är Produkt gëtt reservéiert",
        "loading_msg_header": "W.e.g. waart e Moment",
        "select": "Auswielen",
        "month" : "Monat",
        "year" : "Joer",
        "january":"01 (Jan)",
        "february":"02 (Feb)",
        "march":"03 (Mär)",
        "april":"04 (Apr)",
        "may":"05 (Mee)",
        "june":"06 (Jun)",
        "july":"07 (Jul)",
        "august":"08 (Aug)",
        "september":"09 (Sep)",
        "october":"10 (Okt)",
        "november":"11 (Nov)",
        "december":"12 (Dez)",
        "klarna_billing_information": "Rechnungsinformatiounen",
        "klarna_email_placeholder":"Bevorzugt E-Mail-Adress",
        "klarna_fname_placeholder":"Virnumm",
        "klarna_lname_placeholder":"Familljennumm",
        "klarna_address1_placeholder":"Stroossadress",
        "klarna_address2_placeholder" :"Apt / Suite / Anescht",
        "klarna_city_placeholder" :"Stad",
        "klarna_state_province" :"-- Wielt Staat / Provënz --",
        "klarna_postal_code" :"Postleitzuel",
        "klarna_continue_with_text":"Weidermaachen mat",
        "trust_rating_popup_headertext": "Wéi bewäert Dir Är Kaferfaahrung?",
        "trust_rating_popup_subtext":"Är Feedback bedeit vill",
        "trust_rating_buttontext": "Ofschécken",
        "required":"Obligatorescht Feld",
        "invalid_exp_date": "Ongültegt Verfallsdatum",
        "error-msg-header":"Bezuelung gescheitert. W.e.g. iwwerpréift Är Detailer oder benotzt eng aner Bezuelmethod.<br/><br/>Grond(grënn):",
        "wallet-payment-phone-header":"W.e.g. fëllt déi obligatoresch Felder hei ënnen aus fir eng glat a erfollegräich Liwwerung vun Ärer Bestellung ze garantéieren.",
        "wallet-payment-submit-text": "Ofschécken",
        "invalid_cpf": "W.e.g. gitt eng gülteg CPF-Nummer an.",
        "invalid_houseno": "W.e.g. gitt d'Hausnummer an.",
        "invalid_bairro": "W.e.g. gitt de Bairro an.",
        "invalid_neighborhood": "W.e.g. gitt de Quartier an.",
        "something_wrong":"Eppes ass schif gaang. ",
        "retry": "Nach eng Kéier probéieren",
        "invalid_consigneeId": "Ongülteg Empfänger-ID",
        "phone_number" : "Telefonsnummer:",
        "consignee_id" : "Empfänger-ID:",
        "cpf" : "CPF (Individuell Steierpflechtegregistratur):",
        "pccc" : "PCCC (Perséinlechen Zollbefreiungscode):",
        "invalid_code_id": "Ongültege Code oder ID",
        "paymentMethod_not_return":"PaymentMethod-ID gouf net zréckginn. W.e.g. probéiert et méi spéit nach eng Kéier.",
        "invalid_tax_id": "Ongültege Code oder Steier-ID",
        'invalid_district': 'W.e.g. gitt de District an',
        'invalid_village': 'W.e.g. gitt d\'Duerf an',
        'invalid_apt_unit': 'W.e.g. gitt d\'Appartement-/Eenheetsnummer an',
        'invalid_county': 'W.e.g. gitt de Krees an',
        'invalid_ward': 'W.e.g. gitt de Quartier an',
        'invalid_address1': 'W.e.g. gitt d\'Adress an',
        'unable_to_load_suggestions': 'Virschléi konnte net geluede ginn',
        'searching': 'Sichen...',
        "record_not_found": "Opzeechnung net fonnt",
        "invalid_zip_no": "4 Zifferen.",
        "invalid_city_no": "Gitt als éischt d'Postleitzuel an.",
        "invalid_address_1_no": "Gitt d'Stroossadres an d'Hausnummer an.",
        "invalid_zip_lu": "4 Zifferen",
        "invalid_city_lu": "Gitt als éischt de Postleitzuel an.",
        "invalid_address_1_lu": "Gitt d'Zuel an d'Strooss an.",
        "invalid_address_gr": "Gitt Är Stroossadres un.",
        "invalid_zip_gr": "5 Zifferen.",
        "invalid_city_gr": "Gitt an d'Stad eran.",
        "invalid_address_rs": "Gitt d'Strooss an d'Hausnummer an.",
        "invalid_zip_rs": "5 Zifferen.",
        "invalid_city_rs": "Gitt an d'Stad oder an d'Gemeng."
}
