window.i18nData = {
    "invalid_email": "Vennligst oppgi en gyldig e-postadresse",
    "invalid_fname": "Ugyldig fornavn.",
    "invalid_lname": "Ugyldig etternavn.",
    "invalid_phone": "Ugyldig telefonnummer.",
    "invalid_cc_month": "Ugyldig utløpsmåned for kortet.",
    "invalid_cc_year": "Ugyldig utløpsår for kortet.",
    "invalid_cc": "Ugyldig kredittkortnummer.",
    "invalid_cvv": "Ugyldig kortverifiseringsverdi.",
    "invalid_billing_fname": "Ugyldig fornavn på fakturaen.",
    "invalid_billing_lname": "Ugyldig etternavn på fakturaen.",
    "terms_agree": "Vennligst godta våre vilkår og betingelser.",
    "required_fields": "Obligatoriske felt er markert med rødt",
    "required_fields2": "Vennligst fyll ut de obligatoriske feltene som er markert med rødt.",
    "no_orders": "Det er ingen bestillinger.",
    "decline": "Banken din blokkerer denne betalingen. Vennligst fortsett å bruke denne nettleseren og <b>SVAR PÅ SMS-EN ELLER E-POSTEN FRA BANKEN FOR Å FULLFØRE DENNE BESTILLINGEN</b>. Vennligst sjekk opplysningene dine og prøv på nytt, eller bruk en annen betalingsmåte.<br/><br/>Årsak:",
    "no_item_in_cart": "Det er ingen varer i handlekurven din. Vennligst velg hva du ønsker å bestille.",
    "page_reload": "Siden lastes inn på nytt når du lukker dialogboksen.",
    "invalid_exp_month": "Vennligst oppgi en gyldig måned",
    "invalid_exp_year": "Vennligst oppgi et gyldig årstall.",
    "redirect_to_next": "Du blir omdirigert til neste side.",
    "processing": "Behandler forespørselen...",
    "paypal_processing": "Vennligst vent mens vi omdirigerer deg til PayPal Checkout...",
    "loading_msg": "Produktet ditt blir reservert",
    "loading_msg_header": "Vennligst vent et øyeblikk",
    "select": "Velg",
    "month": "Måned",
    "year": "År",
    "january": "01 (jan)",
    "february": "02 (feb)",
    "march": "03. (mars)",
    "april": "04. (april)",
    "may": "05. (mai)",
    "june": "06. (juni)",
    "july": "07. (juli)",
    "august": "08 (aug.)",
    "september": "09. (sep)",
    "october": "10. (okt.)",
    "november": "11. (nov)",
    "december": "12. (des.)",
    "klarna_billing_information": "Faktureringsopplysninger",
    "klarna_email_placeholder": "Foretrukket e-postadresse",
    "klarna_fname_placeholder": "Fornavn",
    "klarna_lname_placeholder": "Etternavn",
    "klarna_address1_placeholder": "Gateadresse",
    "klarna_address2_placeholder": "Leilighet / Suite / Annet",
    "klarna_city_placeholder": "By",
    "klarna_state_province": "-- Velg delstat / provins --",
    "klarna_postal_code": "Postnummer",
    "klarna_continue_with_text": "Fortsett med",
    "trust_rating_popup_headertext": "Hvordan vil du vurdere handleopplevelsen din?",
    "trust_rating_popup_subtext": "Tilbakemeldingene dine betyr mye for oss",
    "trust_rating_buttontext": "Send inn",
    "required": "Obligatorisk felt",
    "invalid_exp_date": "Ugyldig utløpsdato",
    "error-msg-header": "Betalingen mislyktes. Vennligst sjekk opplysningene dine eller bruk en annen betalingsmåte.<br/><br/>Årsak(er):",
    "wallet-payment-phone-header": "Vennligst fyll ut de obligatoriske feltene nedenfor for å sikre en problemfri og vellykket levering av bestillingen din.",
    "wallet-payment-submit-text": "Send inn",
    "invalid_cpf": "Vennligst oppgi et gyldig CPF-nummer.",
    "invalid_houseno": "Vennligst oppgi husnummer.",
    "invalid_bairro": "Vennligst skriv inn «Bairro».",
    "invalid_neighborhood": "Vennligst gå inn i nabolaget.",
    "something_wrong": "Det oppstod en feil. ",
    "retry": "Prøv på nytt",
    "invalid_consigneeId": "Ugyldig mottaker-ID",
    "phone_number": "Telefonnummer:",
    "consignee_id": "Mottaker-ID:",
    "cpf": "CPF (register over individuelle skattebetalere):",
    "pccc": "PCCC (Personlig tollklareringskode):",
    "invalid_code_id": "Ugyldig kode eller ID",
    "paymentMethod_not_return": "Betalingsmetode-ID ble ikke returnert. Prøv igjen senere.",
    "invalid_tax_id": "Ugyldig kode eller skattenummer",
    "invalid_district": "Vennligst oppgi distrikt",
    "invalid_village": "Vennligst oppgi landsby",
    "invalid_apt_unit": "Vennligst oppgi leilighets-/enhetsnummer",
    "invalid_county": "Vennligst oppgi fylke",
    "invalid_ward": "Vennligst oppgi avdeling",
    "invalid_address1": "Vennligst oppgi adresse",
    "unable_to_load_suggestions": "Kunne ikke laste inn forslag",
    "searching": "Søker...",
    "record_not_found": "Oppføringen ble ikke funnet",
    "invalid_zip_no": "4 sifre.",
    "invalid_city_no": "Skriv inn postnummeret først.",
    "invalid_address_1_no": "Skriv inn gateadresse og husnummer.",
    "invalid_zip_lu": "4 siffer.",
    "invalid_city_lu": "Skriv inn postnummeret først.",
    "invalid_address_1_lu": "Skriv inn nummer og gate.",
    "invalid_address_gr": "Skriv inn gateadressen din.",
    "invalid_zip_gr": "5 sifre.",
    "invalid_city_gr": "Kjør inn i byen.",
    "invalid_address_rs": "Skriv inn gate og husnummer.",
    "invalid_zip_rs": "5 sifre.",
    "invalid_city_rs": "Skriv inn byen."
}