window.i18nData={
        "invalid_email":"Bitte geben Sie eine gültige E-Mail-Adresse ein", 
        "invalid_fname":"Ungültiger Vorname.", 
        "invalid_lname":"Ungültiger Nachname.", 
        "invalid_phone":"Ungültige Telefonnummer.", 
        "invalid_cc_month":"Ungültiger Ablaufmonat der Karte.", 
        "invalid_cc_year": "Ungültiges Ablaufjahr der Karte.", 
        "invalid_cc":"Ungültige Kreditkartennummer.", 
        "invalid_cvv":"Ungültiger Kartenprüfwert.", 
        "invalid_billing_fname":"Ungültiger Vorname für die Rechnungsstellung.", 
        "invalid_billing_lname":"Ungültiger Nachname für die Rechnungsstellung.", 
        "terms_agree":"Bitte stimmen Sie unseren Allgemeinen Geschäftsbedingungen zu.",
        "required_fields":"Erforderliche Felder sind rot markiert.", 
        "required_fields2" :"Bitte füllen Sie die rot markierten Pflichtfelder aus.", 
        "no_orders":"Es gibt keine Bestellungen.",
        "decline": "Ihre Bank blockiert diese Zahlung. Bitte bleiben Sie in diesem Browser und <b>ANTWORTEN SIE AUF DIE SMS ODER E-MAIL DER BANK, UM DIESE BESTELLUNG ABZUSCHLIESSEN</b>. Bitte überprüfen Sie Ihre Angaben und versuchen Sie es erneut oder verwenden Sie eine andere Zahlungsmethode.<br/><br/>Grund:", 
        "no_item_in_cart": "Ihr Warenkorb ist leer. Bitte wählen Sie Ihre Bestellung aus.", 
        "page_reload":"Die Seite wird neu geladen, nachdem Sie das Dialogfeld geschlossen haben.",
        "invalid_exp_month":"Bitte geben Sie einen gültigen Monat ein.", 
        "invalid_exp_year":"Bitte geben Sie ein gültiges Jahr ein.", 
        "redirect_to_next":"Weiterleitung zur nächsten Seite.",
        "processing":"Anfrage wird bearbeitet...", 
        "paypal_processing":"Bitte warten Sie, während wir Sie zur PayPal-Kasse weiterleiten...", 
        "loading_msg":"Ihr Produkt wird reserviert",
        "loading_msg_header": "Bitte warten Sie einen Moment",
        "select": "Auswählen", 
        "month" : "Monat", 
        "year" : "Jahr",
        "january":"01 (Jan)",
        "february":"02 (Februar)",
        "march":"03 (März)",
        "april":"04 (Apr)",
        "may":"05 (Mai)",
        "june":"06 (Juni)",
        "july":"07 (Juli)",
        "august":"08 (Aug)",
        "september":"09 (Sep)",
        "october":"10 (Oct)",
        "november":"11 (Nov)",
        "december":"12 (Dez)",
        "klarna_billing_information": "Rechnungsdaten",
        "klarna_email_placeholder":"Bevorzugte E-Mail-Adresse",
        "klarna_fname_placeholder":"Vorname",
        "klarna_lname_placeholder":"Nachname",
        "klarna_address1_placeholder":"Straße und Hausnummer",
        "klarna_address2_placeholder" :"Wohnung / Suite / Sonstiges",
        "klarna_city_placeholder" :"Stadt",
        "klarna_state_province" :"Bundesland/Provinz auswählen",
        "klarna_postal_code" :"Postleitzahl",
        "klarna_continue_with_text":"Weiter mit",
        "trust_rating_popup_headertext": "Wie würden Sie Ihr Einkaufserlebnis bewerten?",
        "trust_rating_popup_subtext":"Ihr Feedback bedeutet uns sehr viel.",
        "trust_rating_buttontext": "Einreichen",
        "required":"Pflichtfeld",
        "invalid_exp_date": "Ungültiges Ablaufdatum",
        "error-msg-header":"Die Zahlung ist fehlgeschlagen. Bitte überprüfen Sie Ihre Angaben oder verwenden Sie eine andere Zahlungsmethode.<br/><br/>Grund(e):",
        "wallet-payment-phone-header":"Bitte füllen Sie die folgenden Pflichtfelder aus, um eine reibungslose und erfolgreiche Lieferung Ihrer Bestellung zu gewährleisten.",
        "wallet-payment-submit-text": "Einreichen",
        "invalid_cpf": "Bitte geben Sie eine gültige CPF-Nummer ein.",
        "invalid_houseno": "Bitte Hausnummer eingeben.",
        "invalid_bairro": "Bitte geben Sie Bairro ein.",
        "invalid_neighborhood": "Voer de buurt in.",
        "something_wrong":"Es ist ein Fehler aufgetreten.",
        "retry": "Erneut versuchen",
        "invalid_consigneeId": "Ungültige Empfänger-ID",
        "phone_number" : "Telefonnummer:",
        "consignee_id" : "Empfänger-ID:",
        "cpf" : "CPF (Steuerregister für natürliche Personen):",        
        "pccc" : "PCCC (Persönlicher Zollabfertigungscode):",
        "invalid_code_id": "Ungültiger Code oder ungültige ID",
        "paymentMethod_not_return":"Die Zahlungsmethoden-ID wurde nicht zurückgegeben. Bitte versuchen Sie es später erneut.",
        "invalid_tax_id": "Ongeldige code of btw-nummer",
        'invalid_district': 'Voer het district in',
        'invalid_village': 'Voer het dorp in',
        'invalid_apt_unit': 'Voer het appartement-/unitnummer in',
        'invalid_county': 'Voer de provincie in',
        'invalid_ward': 'Voer de wijk in',
        'invalid_address1': 'Voer het adres in',
        'unable_to_load_suggestions': 'Suggesties konden niet worden geladen',
        'searching': 'Zoeken...',
        "record_not_found": "Record niet gevonden",
        "invalid_zip_no": "4 cijfers.",
        "invalid_city_no": "Voer eerst de postcode in.",
        "invalid_address_1_no": "Voer het adres en het huisnummer in.",
        "invalid_zip_lu": "4 cijfers.",
        "invalid_city_lu": "Voer eerst de postcode in.",
        "invalid_address_1_lu": "Voer het huisnummer en de straatnaam in."
}