window.i18nData={
        "invalid_email":"Wprowadź prawidłowy adres e-mail.",
        "invalid_fname":"Nieprawidłowe imię.",
        "invalid_lname":"Nieprawidłowe nazwisko.",
        "invalid_phone":"Nieprawidłowy numer telefonu.",
        "invalid_cc_month":"Nieprawidłowy miesiąc ważności karty.",
        "invalid_cc_year": "Nieprawidłowy rok ważności karty.",
        "invalid_cc":"Nieprawidłowy numer karty kredytowej.",
        "invalid_cvv":"Nieprawidłowy kod weryfikacyjny karty (CVV).",
        "invalid_billing_fname":"Nieprawidłowe imię na fakturze.",
        "invalid_billing_lname":"Nieprawidłowe nazwisko na fakturze.",
        "terms_agree":"Proszę zaakceptować regulamin i warunki.",
        "required_fields":"Wymagane pola zaznaczone na czerwono",
        "required_fields2":"Proszę wypełnić wymagane pola zaznaczone na czerwono.",
        "no_orders":"Brak zamówień.",
        "decline": "Twój bank blokuje tę płatność. Pozostań w tej przeglądarce i <b>ODPOWIEDZ NA SMS LUB E-MAIL Z BANKU, ABY DOKOŃCZYĆ ZAMÓWIENIE</b>. Sprawdź swoje dane i spróbuj ponownie lub użyj innej metody płatności.<br/><br/>Powód:",
        "no_item_in_cart": "Twój koszyk jest pusty. Proszę wybrać produkty do zamówienia.",
        "page_reload":"Strona zostanie odświeżona po zamknięciu okna dialogowego.",
        "invalid_exp_month":"Proszę podać prawidłowy miesiąc.",
        "invalid_exp_year":"Proszę podać prawidłowy rok.",
        "redirect_to_next":"Przekierowanie na następną stronę.",
        "processing":"Przetwarzanie żądania...",
        "paypal_processing":"Proszę czekać, przekierowujemy Cię do płatności PayPal...",
        "loading_msg":"Twój produkt jest rezerwowany",
        "loading_msg_header": "Proszę chwilę poczekać",
        "select": "Wybierz województwo",
        "month" : "Miesiąc",
        "year" : "Rok",
        "january":"01 (Sty)",
        "february":"02 (Lut)",
        "march":"03 (Mar)",
        "april":"04 (Kwi)",
        "may":"05 (Maj)",
        "june":"06 (Cze)",
        "july":"07 (Lip)",
        "august":"08 (Sie)",
        "september":"09 (Wrz)",
        "october":"10 (Paź)",
        "november":"11 (Lis)",
        "december":"12 (Gru)",
        "klarna_billing_information": "Dane do faktury",
        "klarna_email_placeholder":"Preferowany adres e-mail",
        "klarna_fname_placeholder":"Imię",
        "klarna_lname_placeholder":"Nazwisko",
        "klarna_address1_placeholder":"Ulica i numer",
        "klarna_address2_placeholder":"Mieszkanie / Lokal / Inne",
        "klarna_city_placeholder":"Miasto",
        "klarna_state_province":"-- Wybierz województwo --",
        "klarna_postal_code":"Kod pocztowy",
        "klarna_continue_with_text":"Kontynuuj z",
        "trust_rating_popup_headertext": "Jak oceniasz swoje doświadczenie zakupowe?",
        "trust_rating_popup_subtext":"Twoja opinia jest dla nas bardzo ważna",
        "trust_rating_buttontext": "Wyślij",
        "required":"Pole wymagane",
        "invalid_exp_date": "Nieprawidłowa data ważności",
        "error-msg-header":"Płatność nie powiodła się. Sprawdź swoje dane lub użyj innej metody płatności.<br/><br/>Powód(y):",
        "wallet-payment-phone-header":"Proszę wypełnić wymagane pola poniżej, aby zapewnić sprawną i pomyślną dostawę zamówienia.",
        "wallet-payment-submit-text": "Wyślij",
        "invalid_cpf": "Proszę podać prawidłowy numer CPF.",
        "invalid_houseno": "Proszę podać numer domu.",
        "invalid_bairro": "Proszę podać dzielnicę (Bairro).",
        "invalid_neighborhood": "Proszę podać dzielnicę.",
        "something_wrong":"Coś poszło nie tak. ",
        "retry": "Spróbuj ponownie",
        "invalid_consigneeId": "Nieprawidłowy identyfikator odbiorcy",
        "phone_number" : "Numer telefonu:",
        "consignee_id" : "Identyfikator odbiorcy:",
        "cpf" : "CPF (Rejestr Podatnika Indywidualnego):",
        "pccc" : "PCCC (Osobisty Kod Odprawy Celnej):",
        "invalid_code_id": "Nieprawidłowy kod lub identyfikator",
        "paymentMethod_not_return":"Nie zwrócono identyfikatora metody płatności. Proszę spróbować ponownie później.",
        "invalid_tax_id": "Nieprawidłowy kod lub NIP",
        'invalid_district': 'Wprowadź dzielnicę',
        'invalid_village': 'Wprowadź wieś',
        'invalid_apt_unit': 'Wprowadź numer mieszkania/lokalu',
        'invalid_county': 'Wprowadź powiat',
        'invalid_ward': 'Wprowadź dzielnicę',
        'invalid_address1': 'Wprowadź adres',
        'unable_to_load_suggestions': 'Nie można załadować sugestii',
        'searching': 'Wyszukiwanie...',
        "record_not_found": "Nie znaleziono wpisu",
        "invalid_zip_no": "4 cyfry.",
        "invalid_city_no": "Najpierw wprowadź kod pocztowy.",
        "invalid_address_1_no": "Wprowadź nazwę ulicy i numer domu.",
        "invalid_zip_lu": "4 cyfry.",
        "invalid_city_lu": "Najpierw wprowadź kod pocztowy.",
        "invalid_address_1_lu": "Wpisz numer i nazwę ulicy.",
        "invalid_address_gr": "Wpisz swój adres.",
        "invalid_zip_gr": "5 cyfr.",
        "invalid_city_gr": "Wjedź do miasta."
}