window.i18nData={
        "invalid_email":"Por favor, insira um endereço de e-mail válido.", 
        "invalid_fname":"Nome inválido.", 
        "invalid_lname":"Sobrenome inválido.", 
        "invalid_phone":"Número de telefone inválido.", 
        "invalid_cc_month":"Mês de validade do cartão inválido.", 
        "invalid_cc_year": "Ano de validade do cartão inválido.", 
        "invalid_cc":"Número de cartão de crédito inválido.", 
        "invalid_cvv":"Valor de verificação do cartão inválido.", 
        "invalid_billing_fname":"Nome de cobrança inválido.", 
        "invalid_billing_lname":"Sobrenome de cobrança inválido.", 
        "terms_agree":"Por favor, concorde com nossos termos e condições.",
        "required_fields":"Campos obrigatórios destacados em vermelho", 
        "required_fields2" :"Preencha os campos obrigatórios destacados em vermelho.", 
        "no_orders":"Não há pedidos.",
        "decline": "O seu banco está bloqueando este pagamento. Por favor, permaneça neste navegador e <b>RESPONDA À MENSAGEM DE TEXTO OU E-MAIL DO BANCO PARA CONCLUIR ESTE PEDIDO</b>. Verifique suas informações e tente novamente ou utilize um método de pagamento diferente.<br/><br/>Motivo:", 
        "no_item_in_cart": "Não há itens no seu carrinho. Selecione o seu pedido.", 
        "page_reload":"A página será recarregada após você fechar a caixa de diálogo.",
        "invalid_exp_month":"Insira um mês válido", 
        "invalid_exp_year":"Insira um ano válido.", 
        "redirect_to_next":"Redirecionando para a próxima página.",
        "processing":"Processando solicitação...", 
        "paypal_processing":"Aguarde enquanto redirecionamos você para o checkout do PayPal...", 
        "loading_msg":"Seu produto está sendo reservado",
        "loading_msg_header": "Por favor, aguarde um momento",
        "select": "Selecionar", 
        "month" : "Mês", 
        "year" : "Ano",
        "january":"01 (janeiro)",
        "february":"02 (fevereiro)",
        "march":"03 (março)",
        "april":"04 (abril)",
        "may":"05 (maio)",
        "june":"06 (junho)",
        "july":"07 (julho)",
        "august":"08 (agosto)",
        "september":"09 (setembro)",
        "october":"10 (outubro)",
        "november":"11 (novembro)",
        "december":"12 (dezembro)",
        "klarna_billing_information": "Informações de cobrança",
        "klarna_email_placeholder":"Endereço de e-mail preferencial",
        "klarna_fname_placeholder":"Nome",
        "klarna_lname_placeholder":"Sobrenome",
        "klarna_address1_placeholder":"Endereço",
        "klarna_address2_placeholder" :"Apartamento / Suíte / Outro",
        "klarna_city_placeholder" :"Cidade",
        "klarna_state_province" :"-- Selecione o estado/província --",
        "klarna_postal_code" :"Código postal",
        "klarna_continue_with_text":"Continue com",
        "trust_rating_popup_headertext": "Como você avalia sua experiência de compra?",
        "trust_rating_popup_subtext":"A sua opinião é muito importante para nós.",
        "trust_rating_buttontext": "Enviar",
        "invalid_cpf": "Por favor, informe um CPF válido.",
        "invalid_houseno": "Por favor, insira o número da casa.",
        "invalid_bairro": "Por favor, insira o bairro",
        "invalid_neighborhood": "Por favor, insira o bairro.",
        "required":"Campo obrigatório",
        "invalid_exp_date": "Data de validade inválida",
        "error-msg-header":"Falha no pagamento. Verifique seus dados ou utilize um método de pagamento diferente.<br/><br/> Motivo(s):",
        "wallet-payment-phone-header":"Preencha os campos obrigatórios abaixo para garantir que sua encomenda seja entregue sem problemas e com sucesso.",
        "wallet-payment-submit-text": "Enviar",
        "something_wrong":"Algo deu errado.",
        "retry": "Tentar novamente",
        "invalid_consigneeId": "ID do destinatário inválido",
        "phone_number" : "Número de telefone:",
        "consignee_id" : "ID do destinatário:",
        "cpf" : "CPF (Cadastro de Pessoas Físicas):",
        "pccc" : "PCCC (Código de Desembaraço Aduaneiro Pessoal):",
        "invalid_code_id": "Código ou ID inválido",
        "paymentMethod_not_return":"O ID do método de pagamento não foi retornado. Tente novamente mais tarde.",
        "invalid_tax_id": "Código ou CPF/CNPJ inválido",
        'invalid_district': 'Digite o distrito',
        'invalid_village': 'Digite a localidade',
        'invalid_apt_unit': 'Digite o número do apartamento/unidade',
        'invalid_county': 'Digite o município',
        'invalid_ward': 'Digite o bairro',
        'invalid_address1': 'Digite o endereço',
        'unable_to_load_suggestions': 'Não foi possível carregar as sugestões',
        'searching': 'Pesquisando...',
        "record_not_found": "Registro não encontrado",
        "invalid_zip_no": "4 dígitos.",
        "invalid_city_no": "Digite primeiro o código postal.",
        "invalid_address_1_no": "Digite o nome da rua e o número.",
        "invalid_zip_lu": "4 dígitos.",
        "invalid_city_lu": "Digite primeiro o código postal.",
        "invalid_address_1_lu": "Digite o número e o nome da rua.",
        "invalid_address_gr": "Digite seu endereço.",
        "invalid_zip_gr": "5 dígitos.",
        "invalid_city_gr": "Entre na cidade.",
        "invalid_address_rs": "Digite o nome da rua e o número da casa.",
        "invalid_zip_rs": "5 dígitos.",
        "invalid_city_rs": "Digite o nome da cidade.",
        "invalid_address_ch": "Insira o nome da rua e o número da casa.",
        "invalid_zip_ch": "4 dígitos.",
        "invalid_city_ch": "Insira o nome de uma cidade.",
        "invalid_value_zh_hant": "Digite seu endereço em chinês tradicional."
}