window.i18nData={
        "invalid_email":"Por favor, introduza um endereço de e-mail válido.",
        "invalid_fname":"Nome inválido.",
        "invalid_lname":"Apelido inválido.",
        "invalid_phone":"Número de telefone inválido.",
        "invalid_cc_month":"Mês de validade do cartão inválido.",
        "invalid_cc_year": "Ano de validade do cartão inválido.",
        "invalid_cc":"Número de cartão de crédito inválido.",
        "invalid_cvv":"Valor de verificação do cartão inválido.",
        "invalid_billing_fname":"Nome próprio de faturação inválido.",
        "invalid_billing_lname":"Sobrenome de faturação inválido.",
        "terms_agree":"Por favor, concorde com os nossos termos e condições.",
        "required_fields":"Campos obrigatórios destacados a vermelho",
        "required_fields2" :"Preencha os campos obrigatórios destacados a vermelho.",
        "no_orders":"Não há encomendas.",
        "decline": "O seu banco está a bloquear este pagamento. Por favor, permaneça neste navegador e <b>RESPONDA À MENSAGEM DE SMS OU E-MAIL DO BANCO PARA CONCLUIR ESTE PEDIDO</b>. Verifique as suas informações e tente novamente ou utilize um método de pagamento diferente.<br/><br/>Motivo:",
        "no_item_in_cart": "Não há itens no seu carrinho. Selecione o seu pedido.",
        "page_reload":"A página será recarregada após fechar a caixa de diálogo.",
        "invalid_exp_month":"Por favor, insira um mês válido",
        "invalid_exp_year":"Por favor, introduza um ano válido.",
        "redirect_to_next":"Redirecionando para a próxima página.",
        "processing":"Processando pedido...",
        "paypal_processing":"Aguarde enquanto o redirecionamos para o PayPal Checkout...",
        "loading_msg":"O seu produto está a ser reservado",
        "loading_msg_header": "Por favor, aguarde um momento",
        "select": "Selecionar",
        "month" : "Mês",
        "year" : "Ano",
        "january":"01 (Janeiro)",
        "february":"02 (Fevereiro)",
        "march":"03 (Março)",
        "april":"04 (Abril)",
        "may":"05 (Maio)",
        "june":"06 (Junho)",
        "july":"07 (Julho)",
        "august":"08 (Agosto)",
        "september":"09 (Setembro)",
        "october":"10 (Outubro)",
        "november":"11 (Novembro)",
        "december":"12 (Dezembro)",
        "klarna_billing_information": "Informações de faturação",
        "klarna_email_placeholder":"Endereço de e-mail preferencial",
        "klarna_fname_placeholder":"Nome próprio",
        "klarna_lname_placeholder":"Apelido",
        "klarna_address1_placeholder":"Endereço",
        "klarna_address2_placeholder" :"Apartamento / Suíte / Outro",
        "klarna_city_placeholder" :"Cidade",
        "klarna_state_province" :"-- Selecione o estado/província --",
        "klarna_postal_code" :"Código postal",
        "klarna_continue_with_text":"Continuar com",
        "trust_rating_popup_headertext": "Como avalia a sua experiência de compra?",
        "trust_rating_popup_subtext":"A sua opinião é muito importante para nós.",
        "trust_rating_buttontext": "Enviar",
        "required":"Campo obrigatório",
        "invalid_exp_date": "Data de validade inválida",
        "error-msg-header":"O pagamento falhou. Verifique os seus dados ou utilize um método de pagamento diferente.<br/><br/>Motivo(s):",
        "wallet-payment-phone-header":"Preencha os campos obrigatórios abaixo para garantir uma entrega rápida e sem problemas da sua encomenda.",
        "wallet-payment-submit-text": "Enviar",
        "invalid_cpf": "Por favor, informe um CPF válido.",
        "invalid_houseno": "Por favor, insira o número da casa.",
        "invalid_bairro": "Por favor, insira o bairro.",
        "invalid_neighborhood": "Por favor, insira o bairro.",
        "something_wrong":"Algo correu mal.",
        "retry": "Tentar novamente",
        "invalid_consigneeId": "ID do destinatário inválido",
        "phone_number" : "Número de telefone:",
        "consignee_id" : "N.º de identificação do destinatário:",
        "cpf" : "CPF (Registo de Contribuintes):",
        "pccc" : "PCCC (Código Pessoal de Desembaraço Aduaneiro):",
        "invalid_code_id": "Código ou ID inválido",
        "paymentMethod_not_return":"O ID do método de pagamento não foi devolvido. Por favor, tente novamente mais tarde.",
        "invalid_tax_id": "Código ou NIF inválido",
        'invalid_district': 'Introduza o distrito',
        'invalid_village': 'Introduza a localidade',
        'invalid_apt_unit': 'Introduza o número do apartamento/unidade',
        'invalid_county': 'Introduza o concelho',
        'invalid_ward': 'Introduza a freguesia',
        'invalid_address1': 'Introduza a morada',
        'unable_to_load_suggestions': 'Não foi possível carregar as sugestões',
        'searching': 'A pesquisar...'


}
