window.i18nData={
        "invalid_email":"Vă rugăm să introduceți o adresă de email validă",
        "invalid_fname":"Prenume invalid.",
        "invalid_lname":"Nume de familie invalid.",
        "invalid_phone":"Număr de telefon invalid.",
        "invalid_cc_month":"Luna de expirare a cardului este invalidă.",
        "invalid_cc_year":"Anul de expirare a cardului este invalid.",
        "invalid_cc":"Număr de card de credit invalid.",
        "invalid_cvv":"Codul de verificare a cardului este invalid.",
        "invalid_billing_fname":"Prenumele de facturare este invalid.",
        "invalid_billing_lname":"Numele de familie de facturare este invalid.",
        "terms_agree":"Vă rugăm să acceptați termenii și condițiile noastre.",
        "required_fields":"Câmpurile obligatorii sunt evidențiate cu roșu",
        "required_fields2":"Vă rugăm să completați câmpurile obligatorii evidențiate cu roșu.",
        "no_orders":"Nu există comenzi.",
        "decline":"Banca dvs. blochează această plată. Vă rugăm să rămâneți pe acest browser și <b>SĂ RĂSPUNDEȚI LA SMS-UL SAU EMAIL-UL BĂNCII PENTRU A FINALIZA ACEASTĂ COMANDĂ</b>. Vă rugăm să verificați informațiile și să încercați din nou sau să utilizați o altă metodă de plată.<br/><br/>Motiv:",
        "no_item_in_cart":"Nu există articole în coșul dvs. Vă rugăm să selectați comanda.",
        "page_reload":"Pagina se va reîncărca după ce închideți dialogul.",
        "invalid_exp_month":"Vă rugăm să introduceți o lună validă",
        "invalid_exp_year":"Vă rugăm să introduceți un an valid.",
        "redirect_to_next":"Redirecționare către pagina următoare.",
        "processing":"Se procesează cererea...",
        "paypal_processing":"Vă rugăm să așteptați în timp ce vă redirecționăm către PayPal Checkout...",
        "loading_msg":"Produsul dvs. este rezervat",
        "loading_msg_header":"Vă rugăm să așteptați un moment",
        "select":"Selectați",
        "month":"Lună",
        "year":"An",
        "january":"01 (Ian)",
        "february":"02 (Feb)",
        "march":"03 (Mar)",
        "april":"04 (Apr)",
        "may":"05 (Mai)",
        "june":"06 (Iun)",
        "july":"07 (Iul)",
        "august":"08 (Aug)",
        "september":"09 (Sep)",
        "october":"10 (Oct)",
        "november":"11 (Nov)",
        "december":"12 (Dec)",
        "klarna_billing_information":"Informații de facturare",
        "klarna_email_placeholder":"Adresa de email preferată",
        "klarna_fname_placeholder":"Prenume",
        "klarna_lname_placeholder":"Nume de familie",
        "klarna_address1_placeholder":"Adresă stradală",
        "klarna_address2_placeholder":"Apartament / Etaj / Altele",
        "klarna_city_placeholder":"Oraș",
        "klarna_state_province":"-- Selectați județul / provincia --",
        "klarna_postal_code":"Cod poștal",
        "klarna_continue_with_text":"Continuați cu",
        "trust_rating_popup_headertext":"Cum ați evalua experiența dvs. de cumpărături?",
        "trust_rating_popup_subtext":"Opinia dvs. contează mult pentru noi",
        "trust_rating_buttontext":"Trimite",
        "required":"Câmp obligatoriu",
        "invalid_exp_date":"Dată de expirare invalidă",
        "error-msg-header":"Plata a eșuat. Vă rugăm să verificați datele sau să utilizați o altă metodă de plată.<br/><br/>Motiv(e):",
        "wallet-payment-phone-header":"Vă rugăm să completați câmpul (câmpurile) obligatoriu de mai jos pentru a asigura livrarea corectă și cu succes a comenzii dvs.",
        "wallet-payment-submit-text":"Trimite",
        "invalid_cpf":"Vă rugăm să introduceți un număr CPF valid.",
        "invalid_houseno":"Vă rugăm să introduceți numărul casei.",
        "invalid_bairro":"Vă rugăm să introduceți Bairro.",
        "invalid_neighborhood":"Vă rugăm să introduceți cartierul.",
        "something_wrong":"A apărut o eroare. ",
        "retry":"Reîncercați",
        "invalid_consigneeId":"ID destinatar invalid",
        "phone_number":"Număr de telefon:",
        "consignee_id":"ID destinatar:",
        "cpf":"CPF (Registrul individual al contribuabililor):",
        "pccc":"PCCC (Codul personal de vămuire):",
        "invalid_code_id":"Cod sau ID invalid",
        "paymentMethod_not_return":"ID-ul metodei de plată nu a fost returnat. Vă rugăm să încercați din nou mai târziu.",
        "invalid_tax_id":"Cod sau ID fiscal invalid",
        'invalid_district': 'Introduceți districtul',
        'invalid_village': 'Introduceți satul',
        'invalid_apt_unit': 'Introduceți numărul apartamentului/unității',
        'invalid_county': 'Introduceți județul',
        'invalid_ward': 'Introduceți sectorul',
        'invalid_address1': 'Introduceți adresa',
        'unable_to_load_suggestions': 'Sugestiile nu au putut fi încărcate',
        'searching': 'Se caută...',
        'invalid_state_ro': 'Selectează județul.',
        'invalid_city_ro': 'Selectează localitatea.',
        'invalid_zip_ro': '6 cifre.',
        'invalid_address1_ro': 'Introdu strada și numărul.',
        "record_not_found": "Înregistrarea nu a fost găsită",
        "invalid_zip_no": "4 cifre.",
        "invalid_city_no": "Introduceți mai întâi codul poștal.",
        "invalid_address_1_no": "Introduceți adresa și numărul casei.",
        "invalid_zip_lu": "4 cifre.",
        "invalid_city_lu": "Introduceți mai întâi codul poștal.",
        "invalid_address_1_lu": "Introduceți numărul și numele străzii.",
        "invalid_address_gr": "Introduceți adresa dvs.",
        "invalid_zip_gr": "5 cifre.",
        "invalid_city_gr": "Intrați în oraș."
}