window.i18nData={
        "invalid_email":"Unesite važeću adresu e-pošte",
        "invalid_fname":"Nevažeće prvo ime.",
        "invalid_lname":"Nevažeće prezime.",
        "invalid_phone":"Nevažeći telefonski broj.",
        "invalid_cc_month":"Nevažeći mesec isteka kartice.",
        "invalid_cc_year":"Nevažeća godina isteka kartice.",
        "invalid_cc":"Nevažeći broj kreditne kartice.",
        "invalid_cvv":"Nevažeća vrednost za proveru kartice.",
        "invalid_billing_fname":"Nevažeće ime za naplatu.",
        "invalid_billing_lname":"Nevažeće prezime za naplatu.",
        "terms_agree":"Molimo vas da prihvatite naše uslove i odredbe.",
        "required_fields":"Obavezna polja su označena crvenom bojom",
        "required_fields2":"Molimo vas da popunite obavezna polja označena crvenom bojom.",
        "no_orders":"Nema naloga.",
        "decline":"Vaša banka blokira ovaj plaćaj. Molimo vas da ostanete u ovom pregledaču i <b>odgovorite banci putem SMS-a ili e-pošte kako biste dovršili ovu porudžbinu</b>. Molimo vas da proverite svoje podatke i pokušate ponovo ili iskoristite drugi način plaćanja.<br/><br/> Razlog:",
        "no_item_in_cart":"U vašoj kolici nema predmeta. Molimo izaberite porudžbinu.",
        "page_reload":"Stranica će se ponovo učitati nakon što zatvorite dijalog.",
        "invalid_exp_month":"Unesite važeći mesec",
        "invalid_exp_year":"Molimo unesite važeću godinu.",
        "redirect_to_next":"Preusmerava se na sledeću stranicu.",
        "processing":"Obrađuje se zahtev...",
        "paypal_processing":"Molimo sačekajte dok vas preusmeravamo na PayPal Checkout...",
        "loading_msg":"Vaš proizvod se rezerviše",
        "loading_msg_header":"Molim vas, sačekajte trenutak.",
        "select":"Izaberi",
        "month":"Mesec",
        "year":"Godina",
        "january":"01 (Jan)",
        "february":"02 (feb)",
        "march":"03 (Mar)",
        "april":"04 (Apr)",
        "may":"05 (maj)",
        "june":"06 (jun)",
        "july":"07 (Jul)",
        "august":"08 (Avg)",
        "september":"09 (Sep)",
        "october":"10 (okt)",
        "november":"11 (Nov)",
        "december":"12 (Dec)",
        "klarna_billing_information":"Informacije o naplati",
        "klarna_email_placeholder":"Pretpočitana adresa elektronske pošte",
        "klarna_fname_placeholder":"Prvo ime",
        "klarna_lname_placeholder":"Prezime",
        "klarna_address1_placeholder":"Ulična adresa",
        "klarna_address2_placeholder":"Stanović / Apartman / Ostalo",
        "klarna_city_placeholder":"Grad",
        "klarna_state_province":"-- Izaberite državu / provinciju --",
        "klarna_postal_code":"Poštanski broj",
        "klarna_continue_with_text":"Nastavi sa",
        "trust_rating_popup_headertext":"Kako biste ocenili svoje iskustvo kupovine?",
        "trust_rating_popup_subtext":"Vaša povratna informacija mnogo znači",
        "trust_rating_buttontext":"Pošalji",
        "required":"Obavezno polje",
        "invalid_exp_date":"Nevažeći datum isteka",
        "error-msg-header":"Plaćanje nije uspelo. Molimo vas da proverite svoje podatke ili koristite drugi način plaćanja.<br/><br/> Razlog(i):",
        "wallet-payment-phone-header":"Molimo vas da popunite obavezna polja u nastavku kako biste osigurali nesmetan i uspešan dostavu vaše porudžbine.",
        "wallet-payment-submit-text":"Pošalji",
        "invalid_cpf":"Molimo unesite važeći broj CPF.",
        "invalid_houseno":"Molimo unesite broj kuće.",
        "invalid_bairro":"Molimo unesite Bairro.",
        "invalid_neighborhood":"Molimo vas da uđete u komšiluk.",
        "something_wrong":"Nešto je pošlo po zlu. ",
        "retry":"Ponovo pokušaj",
        "invalid_consigneeId":"Nevažeći identifikacioni broj primaoca",
        "phone_number":"Broj telefona:",
        "consignee_id":"Identifikacioni broj primaoca:",
        "cpf":"CPF (Poreski registar pojedinačnih obveznika):",
        "pccc":"PCCC (lični kod za carinsko oformljenje):",
        "invalid_code_id":"Nevažeći kod ili ID",
        "paymentMethod_not_return":"ID načina plaćanja nije vraćen. Molimo pokušajte ponovo kasnije.",
        "invalid_tax_id":"Nevažeći kod ili poreski identifikacioni broj",
        "invalid_district":"Molimo unesite okrug",
        "invalid_village":"Molimo unesite selo",
        "invalid_apt_unit":"Unesite broj stana/jedinice",
        "invalid_county":"Molimo unesite okrug",
        "invalid_ward":"Molimo vas da uđete u odeljenje.",
        "invalid_address1":"Molimo unesite adresu",
        "unable_to_load_suggestions":"Nije moguće učitati predloge",
        "searching":"Pretraga...",
        "record_not_found":"Zapis nije pronađen",
        "invalid_zip_no":"4 cifre.",
        "invalid_city_no":"Prvo unesite poštanski broj.",
        "invalid_address_1_no":"Unesite adresu ulice i broj.",
        "invalid_zip_lu":"4 cifre.",
        "invalid_city_lu":"Prvo unesite poštanski broj.",
        "invalid_address_1_lu":"Unesite broj i ulicu.",
        "invalid_address_gr":"Unesite vašu ulicu.",
        "invalid_zip_gr":"5 cifara.",
        "invalid_city_gr":"Uđite u grad.",
        "invalid_address_rs":"Unesite naziv ulice i broj kuće.",
        "invalid_zip_rs":"5 cifara.",
        "invalid_city_rs":"Unesite grad ili opštinu.",
        "invalid_address_ch": "Молимо унесите назив улице и број куће.",
        "invalid_zip_ch": "4 цифре.",
        "invalid_city_ch": "Молимо унесите град/место."
}