window.i18nData={
        "invalid_email":"Ange en giltig e-postadress", 
        "invalid_fname":"Ogiltigt förnamn.", 
        "invalid_lname":"Ogiltigt efternamn.", 
        "invalid_phone":"Ogiltigt telefonnummer.", 
        "invalid_cc_month":"Ogiltig utgångsmånad för kortet.", 
        "invalid_cc_year": "Ogiltigt utgångsår för kortet.", 
        "invalid_cc":"Ogiltigt kreditkortsnummer.", 
        "invalid_cvv":"Ogiltigt kortverifieringsvärde.", 
        "invalid_billing_fname":"Ogiltigt förnamn för fakturering.", 
        "invalid_billing_lname":"Ogiltigt efternamn för fakturering.", 
        "terms_agree":"Godkänn våra villkor.",
        "required_fields":"Obligatoriska fält är markerade med rött", 
        "required_fields2" :"Fyll i de obligatoriska fälten som är markerade med rött.", 
        "no_orders":"Det finns inga beställningar.",
        "decline": "Din bank blockerar denna betalning. Stanna kvar i den här webbläsaren och <b>SVARA PÅ BANKENS SMS ELLER E-POST FÖR ATT SLUTFÖRA DENNA BESTÄLLNING</b>. Kontrollera dina uppgifter och försök igen eller använd en annan betalningsmetod.<br/><br/>Anledning:", 
        "no_item_in_cart": "Det finns inga artiklar i din kundvagn. Välj din beställning.", 
        "page_reload":"Sidan laddas om när du stänger dialogrutan.",
        "invalid_exp_month":"Ange en giltig månad", 
        "invalid_exp_year":"Ange ett giltigt år.", 
        "redirect_to_next":"Omdirigerar till nästa sida.",
        "processing":"Bearbetar begäran...", 
        "paypal_processing":"Vänta medan vi omdirigerar dig till PayPal Checkout...", 
        "loading_msg":"Din produkt reserveras",
        "loading_msg_header": "Vänta ett ögonblick",
        "select": "Välj", 
        "month" : "Månad", 
        "year" : "År",
        "january":"01 (jan)",
        "february":"02 (feb)",
        "march":"03 (mar)",
        "april":"04 (apr)",
        "may":"05 (maj)",
        "june":"06 (jun)",
        "july":"07 (jul)",
        "august":"08 (aug)",
        "september":"09 (sep)",
        "october":"10 (okt)",
        "november":"11 (nov)",
        "december":"12 (dec)",
        "klarna_billing_information": "Faktureringsinformation",
        "klarna_email_placeholder":"Önskad e-postadress",
        "klarna_fname_placeholder":"Förnamn",
        "klarna_lname_placeholder":"Efternamn",
        "klarna_address1_placeholder":"Gatuadress",
        "klarna_address2_placeholder" :"Lägenhet / Sv / Annat",
        "klarna_city_placeholder" :"Ort",
        "klarna_state_province" :"-- Välj delstat / provins --",
        "klarna_postal_code" :"Postnummer",
        "klarna_continue_with_text":"Fortsätt med",
        "trust_rating_popup_headertext": "Hur skulle du bedöma din shoppingupplevelse?",
        "trust_rating_popup_subtext":"Din feedback betyder mycket",
        "trust_rating_buttontext": "Skicka",
        "required":"Obligatoriskt fält",
        "invalid_exp_date": "Ogiltigt utgångsdatum",
        "error-msg-header":"Betalningen misslyckades. Kontrollera dina uppgifter eller använd en annan betalningsmetod.<br/><br/>Anledning(ar):",
        "wallet-payment-phone-header":"Fyll i de obligatoriska fälten nedan för att säkerställa en smidig och framgångsrik leverans av din beställning.",
        "wallet-payment-submit-text": "Skicka",
        "invalid_cpf": "Ange ett giltigt CPF-nummer.",
        "invalid_houseno": "Ange husnummer.",
        "invalid_bairro": "Ange Bairro.",
        "invalid_neighborhood": "Ange området.",
        "something_wrong":"Något gick fel. ",
        "retry": "Försök igen",
        "invalid_consigneeId": "Ogiltigt mottagar-ID",
        "phone_number" : "Telefonnummer:",
        "consignee_id" : "Mottagar-ID:",
        "cpf" : "CPF (register för enskilda skattskyldiga):",
        "pccc" : "PCCC (personlig tullklareringskod):",
        "invalid_code_id": "Ogiltig kod eller ID",
        "paymentMethod_not_return":"PaymentMethod-ID returnerades inte. Försök igen senare.",
        "invalid_tax_id": "Ogiltig kod eller skatte-ID",
        "invalid_district": "Ange distrikt",
        "invalid_village": "Ange by",
        "invalid_apt_unit": "Ange lägenhets-/enhetsnummer",
        "invalid_county": "Ange kommun",
        "invalid_ward": "Ange valdistrikt",
        "invalid_address1": "Ange adress",
        "unable_to_load_suggestions": "Kunde inte läsa in förslag",
        "searching": "Söker...",
        "record_not_found": "Posten hittades inte"
}
