window.i18nData = {
    "invalid_email":"Mangyaring maglagay ng wastong email address.",
    "invalid_fname":"Hindi wastong unang pangalan.",
    "invalid_lname":"Hindi wastong apelyido.",
    "invalid_phone":"Hindi wastong numero ng telepono.",
    "invalid_cc_month":"Hindi wastong buwan ng pag-expire ng card.",
    "invalid_cc_year":"Hindi wastong taon ng pag-expire ng card.",
    "invalid_cc":"Hindi wastong numero ng credit card.",
    "invalid_cvv":"Hindi wastong CVV o verification code ng card.",
    "invalid_billing_fname":"Hindi wastong unang pangalan sa billing.",
    "invalid_billing_lname":"Hindi wastong apelyido sa billing.",
    "terms_agree":"Pakisang-ayunan ang aming mga tuntunin at kundisyon.",
    "required_fields":"Ang mga kinakailangang field ay naka-highlight sa pula.",
    "required_fields2":"Pakipunan ang mga kinakailangang field na naka-highlight sa pula.",
    "no_orders":"Walang mga order.",
    "decline":"Hinaharang ng iyong bangko ang pagbabayad na ito. Mangyaring manatili sa browser na ito at <b>TUMUGON SA SMS O EMAIL NG BANGKO UPANG MAKUMPLETO ANG ORDER NA ITO</b>. Pakisuri ang iyong impormasyon at subukang muli o gumamit ng ibang paraan ng pagbabayad.<br/><br/>Dahilan:",
    "no_item_in_cart":"Walang laman ang iyong cart. Mangyaring piliin ang iyong order.",
    "page_reload":"Magre-reload ang pahina pagkatapos mong isara ang dialog.",
    "invalid_exp_month":"Mangyaring maglagay ng wastong buwan.",
    "invalid_exp_year":"Mangyaring maglagay ng wastong taon.",
    "redirect_to_next":"Nire-redirect sa susunod na pahina.",
    "processing":"Pinoproseso ang kahilingan...",
    "paypal_processing":"Mangyaring maghintay habang nire-redirect ka sa PayPal Checkout...",
    "loading_msg":"Inilalaan ang Iyong Produkto",
    "loading_msg_header":"Mangyaring maghintay sandali",
    "select":"Pumili",
    "month":"Buwan",
    "year":"Taon",
    "january":"01 (Ene)",
    "february":"02 (Peb)",
    "march":"03 (Mar)",
    "april":"04 (Abr)",
    "may":"05 (May)",
    "june":"06 (Hun)",
    "july":"07 (Hul)",
    "august":"08 (Ago)",
    "september":"09 (Set)",
    "october":"10 (Okt)",
    "november":"11 (Nob)",
    "december":"12 (Dis)",
    "klarna_billing_information":"Impormasyon sa Billing",
    "klarna_email_placeholder":"Piling Email Address",
    "klarna_fname_placeholder":"Unang Pangalan",
    "klarna_lname_placeholder":"Apelyido",
    "klarna_address1_placeholder":"Address ng Kalye",
    "klarna_address2_placeholder":"Apartment / Suite / Iba pa",
    "klarna_city_placeholder":"Lungsod",
    "klarna_state_province":"-- Pumili ng Estado / Probinsya --",
    "klarna_postal_code":"Zip / Postal Code",
    "klarna_continue_with_text":"Magpatuloy gamit ang",
    "trust_rating_popup_headertext":"Paano mo ire-rate ang iyong karanasan sa pamimili?",
    "trust_rating_popup_subtext":"Malaki ang halaga ng iyong feedback",
    "trust_rating_buttontext":"Isumite",
    "required":"Kinakailangang Field",
    "invalid_exp_date":"Hindi wastong petsa ng pag-expire",
    "error-msg-header":"Nabigo ang pagbabayad. Pakisuri ang iyong mga detalye o gumamit ng ibang paraan ng pagbabayad.<br/><br/>Dahilan:",
    "wallet-payment-phone-header":"Mangyaring punan ang mga kinakailangang field sa ibaba upang matiyak ang maayos at matagumpay na paghahatid ng iyong order.",
    "wallet-payment-submit-text":"Isumite",
    "invalid_cpf":"Mangyaring maglagay ng wastong CPF number.",
    "invalid_houseno":"Mangyaring ilagay ang numero ng bahay.",
    "invalid_bairro":"Mangyaring ilagay ang Bairro.",
    "invalid_neighborhood":"Mangyaring ilagay ang kapitbahayan.",
    "something_wrong":"May nangyaring mali.",
    "retry":"Subukang muli",
    "invalid_consigneeId":"Hindi wastong Consignee ID",
    "phone_number":"Numero ng Telepono:",
    "consignee_id":"Consignee ID:",
    "cpf":"CPF (Indibidwal na Rehistro ng Nagbabayad ng Buwis):",
    "pccc":"PCCC (Personal Customs Clearance Code):",
    "invalid_code_id":"Hindi wastong code o ID",
    "paymentMethod_not_return":"Hindi naibalik ang PaymentMethod ID. Pakisubukang muli mamaya.",
    "invalid_tax_id": "Di-wastong code o Tax ID",
    'invalid_district': 'Pakilagay ang distrito',
    'invalid_village': 'Pakilagay ang barangay',
    'invalid_apt_unit': 'Pakilagay ang numero ng apartment/unit',
    'invalid_county': 'Pakilagay ang county',
    'invalid_ward': 'Pakilagay ang ward',
    'invalid_address1': 'Pakilagay ang address',
    'unable_to_load_suggestions': 'Hindi ma-load ang mga mungkahi',
    'searching': 'Naghahanap...',
    "record_not_found": "Hindi nahanap ang tala",
    "invalid_zip_no": "Apat na digit.",
    "invalid_city_no": "Ipasok muna ang postal code.",
    "invalid_address_1_no": "Ipasok ang address ng kalye at numero.",
    "invalid_zip_lu": "Apat na digit.",
    "invalid_city_lu": "Ipasok muna ang postal code.",
    "invalid_address_1_lu": "Ipasok ang numero at ang kalye."
};