window.i18nData={
        "invalid_email":"Lütfen geçerli bir e-posta adresi girin.",
        "invalid_fname":"Geçersiz Ad.",
        "invalid_lname":"Geçersiz Soyad.",
        "invalid_phone":"Geçersiz Telefon Numarası.",
        "invalid_cc_month":"Geçersiz Kart Son Kullanma Ayı.",
        "invalid_cc_year": "Geçersiz Kart Son Kullanma Yılı.",
        "invalid_cc":"Geçersiz Kredi Kartı Numarası.",
        "invalid_cvv":"Geçersiz Kart Doğrulama Değeri.",
        "invalid_billing_fname":"Geçersiz Fatura Adı.",
        "invalid_billing_lname":"Geçersiz Fatura Soyadı.",
        "terms_agree":"Lütfen şartlar ve koşullarımızı kabul edin.",
        "required_fields":"Zorunlu alan(lar) kırmızı ile vurgulandı",
        "required_fields2" :"Lütfen kırmızı ile vurgulanan zorunlu alanları doldurun.",
        "no_orders":"Sipariş bulunmamaktadır.",
        "decline": "Bankanız bu ödemeyi engelliyor. Lütfen bu tarayıcıda kalın ve <b>SİPARİŞİNİZİ TAMAMLAMAK İÇİN BANKANIN SMS'İNE VEYA E-POSTASINA YANIT VERİN</b>. Lütfen bilgilerinizi doğrulayın ve tekrar deneyin ya da farklı bir ödeme yöntemi kullanın.<br/><br/>Neden:",
        "no_item_in_cart": "Sepetinizde ürün bulunmamaktadır. Lütfen siparişinizi seçin.",
        "page_reload":"İletişim kutusunu kapattıktan sonra sayfa yeniden yüklenecektir.",
        "invalid_exp_month":"Lütfen geçerli bir ay girin.",
        "invalid_exp_year":"Lütfen geçerli bir yıl girin.",
        "redirect_to_next":"Bir sonraki sayfaya yönlendiriliyorsunuz.",
        "processing":"İstek işleniyor...",
        "paypal_processing":"Sizi PayPal Ödeme sayfasına yönlendirirken lütfen bekleyin...",
        "loading_msg":"Ürününüz Rezerve Ediliyor",
        "loading_msg_header": "Lütfen bir an bekleyin",
        "select": "Seçin",
        "month" : "Ay",
        "year" : "Yıl",
        "january":"01 (Oca)",
        "february":"02 (Şub)",
        "march":"03 (Mar)",
        "april":"04 (Nis)",
        "may":"05 (May)",
        "june":"06 (Haz)",
        "july":"07 (Tem)",
        "august":"08 (Ağu)",
        "september":"09 (Eyl)",
        "october":"10 (Eki)",
        "november":"11 (Kas)",
        "december":"12 (Ara)",
        "klarna_billing_information": "Fatura Bilgileri",
        "klarna_email_placeholder":"Tercih Edilen E-posta Adresi",
        "klarna_fname_placeholder":"Ad",
        "klarna_lname_placeholder":"Soyad",
        "klarna_address1_placeholder":"Sokak Adresi",
        "klarna_address2_placeholder" :"Daire / Kat / Diğer",
        "klarna_city_placeholder" :"Şehir",
        "klarna_state_province" :"-- İl / İlçe Seçin --",
        "klarna_postal_code" :"Posta Kodu",
        "klarna_continue_with_text":"Devam et",
        "trust_rating_popup_headertext": "Alışveriş deneyiminizi nasıl değerlendirirsiniz?",
        "trust_rating_popup_subtext":"Geri bildiriminiz çok önemli",
        "trust_rating_buttontext": "Gönder",
        "required":"Zorunlu Alan",
        "invalid_exp_date": "Geçersiz Son Kullanma Tarihi",
        "error-msg-header":"Ödeme başarısız oldu. Lütfen bilgilerinizi doğrulayın veya farklı bir ödeme yöntemi kullanın.<br/><br/>Neden(ler):",
        "wallet-payment-phone-header":"Siparişinizin sorunsuz ve başarılı bir şekilde teslim edilmesini sağlamak için lütfen aşağıdaki zorunlu alan(lar)ı doldurun.",
        "wallet-payment-submit-text": "Gönder",
        "invalid_cpf": "Lütfen geçerli bir CPF numarası girin.",
        "invalid_houseno": "Lütfen kapı numarasını girin.",
        "invalid_bairro": "Lütfen Bairro'yu girin.",
        "invalid_neighborhood": "Lütfen mahalleyi girin.",
        "something_wrong":"Bir şeyler ters gitti. ",
        "retry": "Tekrar Dene",
        "invalid_consigneeId": "Geçersiz Alıcı Kimliği",
        "phone_number" : "Telefon Numarası:",
        "consignee_id" : "Alıcı Kimliği:",
        "cpf" : "CPF (Bireysel Vergi Mükellefi Kaydı):",
        "pccc" : "PCCC (Kişisel Gümrük Gümrükleme Kodu):",
        "invalid_code_id": "Geçersiz kod veya kimlik",
        "paymentMethod_not_return":"Ödeme Yöntemi Kimliği döndürülmedi. Lütfen daha sonra tekrar deneyin.",
        "invalid_tax_id": "Geçersiz kod veya Vergi Kimliği",
        'invalid_district': 'Lütfen ilçe girin',
        'invalid_village': 'Lütfen köy girin',
        'invalid_apt_unit': 'Lütfen daire/birim numarası girin',
        'invalid_county': 'Lütfen ilçe girin',
        'invalid_ward': 'Lütfen mahalle girin',
        'invalid_address1': 'Lütfen adres girin',
        'unable_to_load_suggestions': 'Öneriler yüklenemedi',
        'searching': 'Aranıyor...',
        "record_not_found": "Kayıt bulunamadı",
        "invalid_zip_no": "4 basamak.",
        "invalid_city_no": "Önce posta kodunu girin.",
        "invalid_address_1_no": "Sokak adresini ve numarasını girin.",
        "invalid_zip_lu": "4 basamak.",
        "invalid_city_lu": "Önce posta kodunu girin.",
        "invalid_address_1_lu": "Numarayı ve cadde adını girin.",
        "invalid_address_gr": "Sokak adresinizi girin.",
        "invalid_zip_gr": "5 basamak.",
        "invalid_city_gr": "Şehre girin.",
        "invalid_address_rs": "Sokak adını ve ev numarasını girin.",
        "invalid_zip_rs": "5 basamak.",
        "invalid_city_rs": "Kasabayı veya şehri girin."
}