window.i18nData={
        "invalid_email":"براہ کرم ایک درست ای میل ایڈریس درج کریں",
        "invalid_fname":"غلط پہلا نام۔",
        "invalid_lname":"غلط آخری نام۔",
        "invalid_phone":"غلط فون نمبر۔",
        "invalid_cc_month":"کریڈٹ کارڈ کی میعاد ختم ہونے کا مہینہ غلط ہے۔",
        "invalid_cc_year": "کریڈٹ کارڈ کی میعاد ختم ہونے کا سال غلط ہے۔",
        "invalid_cc":"کریڈٹ کارڈ نمبر غلط ہے۔",
        "invalid_cvv":"کارڈ تصدیقی قدر غلط ہے۔",
        "invalid_billing_fname":"بلنگ کا پہلا نام غلط ہے۔",
        "invalid_billing_lname":"بلنگ کا آخری نام غلط ہے۔",
        "terms_agree":"براہ کرم ہماری شرائط و ضوابط سے اتفاق کریں۔",
        "required_fields":"ضروری خانے سرخ رنگ میں نشان زد ہیں",
        "required_fields2" :"براہ کرم سرخ رنگ میں نشان زد ضروری خانے پُر کریں۔",
        "no_orders":"کوئی آرڈر موجود نہیں۔",
        "decline": "آپ کا بینک یہ ادائیگی روک رہا ہے۔ براہ کرم اسی براؤزر پر رہیں اور <b>اس آرڈر کو مکمل کرنے کے لیے بینک کے ایس ایم ایس یا ای میل کا جواب دیں</b>۔ براہ کرم اپنی معلومات تصدیق کریں اور دوبارہ کوشش کریں یا کوئی دوسرا ادائیگی طریقہ استعمال کریں۔<br/><br/>وجہ:",
        "no_item_in_cart": "آپ کی کارٹ میں کوئی آئٹم نہیں ہے۔ براہ کرم اپنا آرڈر منتخب کریں۔",
        "page_reload":"ڈائیلاگ بند کرنے کے بعد صفحہ دوبارہ لوڈ ہو جائے گا۔",
        "invalid_exp_month":"براہ کرم ایک درست مہینہ درج کریں",
        "invalid_exp_year":"براہ کرم ایک درست سال درج کریں۔",
        "redirect_to_next":"اگلے صفحے پر منتقل کیا جا رہا ہے۔",
        "processing":"درخواست پر کارروائی جاری ہے...",
        "paypal_processing":"براہ کرم انتظار کریں، آپ کو پے پال چیک آؤٹ پر بھیجا جا رہا ہے...",
        "loading_msg":"آپ کی مصنوع محفوظ کی جا رہی ہے",
        "loading_msg_header": "براہ کرم ایک لمحہ انتظار کریں",
        "select": "منتخب کریں",
        "month" : "مہینہ",
        "year" : "سال",
        "january":"01 (جنوری)",
        "february":"02 (فروری)",
        "march":"03 (مارچ)",
        "april":"04 (اپریل)",
        "may":"05 (مئی)",
        "june":"06 (جون)",
        "july":"07 (جولائی)",
        "august":"08 (اگست)",
        "september":"09 (ستمبر)",
        "october":"10 (اکتوبر)",
        "november":"11 (نومبر)",
        "december":"12 (دسمبر)",
        "klarna_billing_information": "بلنگ کی معلومات",
        "klarna_email_placeholder":"پسندیدہ ای میل ایڈریس",
        "klarna_fname_placeholder":"پہلا نام",
        "klarna_lname_placeholder":"آخری نام",
        "klarna_address1_placeholder":"گلی کا پتہ",
        "klarna_address2_placeholder" :"اپارٹمنٹ / سوئٹ / دیگر",
        "klarna_city_placeholder" :"شہر",
        "klarna_state_province" :"-- صوبہ / ریاست منتخب کریں --",
        "klarna_postal_code" :"ڈاک کوڈ / پوسٹل کوڈ",
        "klarna_continue_with_text":"جاری رکھیں",
        "trust_rating_popup_headertext": "آپ اپنی خریداری کے تجربے کو کیسے درجہ دیں گے؟",
        "trust_rating_popup_subtext":"آپ کی رائے ہمارے لیے بہت اہم ہے",
        "trust_rating_buttontext": "جمع کروائیں",
        "required":"ضروری خانہ",
        "invalid_exp_date": "میعاد ختم ہونے کی تاریخ غلط ہے",
        "error-msg-header":"ادائیگی ناکام ہوئی۔ براہ کرم اپنی تفصیلات تصدیق کریں یا کوئی دوسرا ادائیگی طریقہ استعمال کریں۔<br/><br/>وجہ(یں):",
        "wallet-payment-phone-header":"براہ کرم اپنے آرڈر کی بآسانی اور کامیاب ترسیل کو یقینی بنانے کے لیے نیچے دیے گئے ضروری خانے پُر کریں۔",
        "wallet-payment-submit-text": "جمع کروائیں",
        "invalid_cpf": "براہ کرم ایک درست CPF نمبر درج کریں۔",
        "invalid_houseno": "براہ کرم مکان نمبر درج کریں۔",
        "invalid_bairro": "براہ کرم Bairro درج کریں۔",
        "invalid_neighborhood": "براہ کرم محلہ درج کریں۔",
        "something_wrong":"کچھ غلط ہو گیا۔ ",
        "retry": "دوبارہ کوشش کریں",
        "invalid_consigneeId": "وصول کنندہ کا شناختی نمبر غلط ہے",
        "phone_number" : "فون نمبر:",
        "consignee_id" : "وصول کنندہ کا شناختی نمبر:",
        "cpf" : "CPF (انفرادی ٹیکس دہندہ رجسٹری):",
        "pccc" : "PCCC (ذاتی کسٹمز کلیئرنس کوڈ):",
        "invalid_code_id": "کوڈ یا شناختی نمبر غلط ہے",
        "paymentMethod_not_return":"ادائیگی کا طریقہ شناختی نمبر واپس نہیں آیا۔ براہ کرم بعد میں دوبارہ کوشش کریں۔",
        "invalid_tax_id": "کوڈ یا ٹیکس شناختی نمبر غلط ہے",
        'invalid_district': 'براہ کرم ضلع درج کریں',
        'invalid_village': 'براہ کرم گاؤں درج کریں',
        'invalid_apt_unit': 'براہ کرم اپارٹمنٹ / یونٹ نمبر درج کریں',
        'invalid_county': 'براہ کرم کاؤنٹی درج کریں',
        'invalid_ward': 'براہ کرم وارڈ درج کریں',
        'invalid_address1': 'براہ کرم پتہ درج کریں',
        'unable_to_load_suggestions': 'تجاویز لوڈ نہیں ہو سکیں',
        'searching': 'تلاش جاری ہے...',
        "record_not_found": "ریکارڈ نہیں ملا",
        "invalid_zip_no": "چار ہندسے",
        "invalid_city_no": "سب سے پہلے پوسٹل کوڈ درج کریں۔",
        "invalid_address_1_no": "سڑک کا پتہ اور نمبر درج کریں۔",
        "invalid_zip_lu": "چار ہندسے",
        "invalid_city_lu": "سب سے پہلے پوسٹل کوڈ درج کریں۔",
        "invalid_address_1_lu": "نمبر اور گلی درج کریں۔",
        "invalid_address_gr": "اپنا گلی کا پتہ درج کریں۔",
        "invalid_zip_gr": "پانچ ہندسے",
        "invalid_city_gr": "شہر میں داخل ہوں۔",
        "invalid_address_rs": "گلی اور گھر کا نمبر درج کریں۔",
        "invalid_zip_rs": "پانچ ہندسے",
        "invalid_city_rs": "قصبے یا شہر میں داخل ہوں۔",
        "invalid_address_ch": "براہ کرم گلی اور گھر کا نمبر درج کریں۔",
        "invalid_zip_ch": "چار ہندسے",
        "invalid_city_ch": "براہ کرم ایک قصبہ/شہر درج کریں۔"
}