window.i18nData={
        "invalid_email":"Vui lòng nhập địa chỉ email hợp lệ",
        "invalid_fname":"Tên không hợp lệ.",
        "invalid_lname":"Họ không hợp lệ.",
        "invalid_phone":"Số điện thoại không hợp lệ.",
        "invalid_cc_month":"Tháng hết hạn thẻ không hợp lệ.",
        "invalid_cc_year": "Năm hết hạn thẻ không hợp lệ.",
        "invalid_cc":"Số thẻ tín dụng không hợp lệ.",
        "invalid_cvv":"Mã bảo mật thẻ không hợp lệ.",
        "invalid_billing_fname":"Tên trên hóa đơn không hợp lệ.",
        "invalid_billing_lname":"Họ trên hóa đơn không hợp lệ.",
        "terms_agree":"Vui lòng đồng ý với điều khoản và điều kiện của chúng tôi.",
        "required_fields":"(Các) trường bắt buộc được đánh dấu màu đỏ",
        "required_fields2" :"Vui lòng điền vào các trường bắt buộc được đánh dấu màu đỏ.",
        "no_orders":"Không có đơn hàng nào.",
        "decline": "Ngân hàng của bạn đang chặn khoản thanh toán này. Vui lòng ở lại trình duyệt này và <b>PHẢN HỒI TIN NHẮN SMS HOẶC EMAIL CỦA NGÂN HÀNG ĐỂ HOÀN TẤT ĐƠN HÀNG NÀY</b>. Vui lòng kiểm tra lại thông tin và thử lại hoặc sử dụng phương thức thanh toán khác.<br/><br/>Lý do:",
        "no_item_in_cart": "Không có sản phẩm nào trong giỏ hàng của bạn. Vui lòng chọn đơn hàng của bạn.",
        "page_reload":"Trang sẽ tải lại sau khi bạn đóng hộp thoại.",
        "invalid_exp_month":"Vui lòng nhập tháng hợp lệ",
        "invalid_exp_year":"Vui lòng nhập năm hợp lệ.",
        "redirect_to_next":"Đang chuyển hướng đến trang tiếp theo.",
        "processing":"Đang xử lý yêu cầu...",
        "paypal_processing":"Vui lòng đợi trong khi chúng tôi chuyển hướng bạn đến PayPal Checkout...",
        "loading_msg":"Sản phẩm của bạn đang được giữ chỗ",
        "loading_msg_header": "Vui lòng đợi trong giây lát",
        "select": "Chọn",
        "month" : "Tháng",
        "year" : "Năm",
        "january":"01 (Th1)",
        "february":"02 (Th2)",
        "march":"03 (Th3)",
        "april":"04 (Th4)",
        "may":"05 (Th5)",
        "june":"06 (Th6)",
        "july":"07 (Th7)",
        "august":"08 (Th8)",
        "september":"09 (Th9)",
        "october":"10 (Th10)",
        "november":"11 (Th11)",
        "december":"12 (Th12)",
        "klarna_billing_information": "Thông Tin Thanh Toán",
        "klarna_email_placeholder":"Email Ưu Tiên",
        "klarna_fname_placeholder":"Tên",
        "klarna_lname_placeholder":"Họ",
        "klarna_address1_placeholder":"Địa Chỉ",
        "klarna_address2_placeholder" :"Căn Hộ / Tầng / Khác",
        "klarna_city_placeholder" :"Thành Phố",
        "klarna_state_province" :"-- Chọn Tỉnh / Thành Phố --",
        "klarna_postal_code" :"Mã Bưu Điện",
        "klarna_continue_with_text":"Tiếp tục với",
        "trust_rating_popup_headertext": "Bạn đánh giá trải nghiệm mua sắm của mình như thế nào?",
        "trust_rating_popup_subtext":"Phản hồi của bạn rất có giá trị với chúng tôi",
        "trust_rating_buttontext": "Gửi",
        "required":"Trường Bắt Buộc",
        "invalid_exp_date": "Ngày hết hạn không hợp lệ",
        "error-msg-header":"Thanh toán không thành công. Vui lòng kiểm tra lại thông tin hoặc sử dụng phương thức thanh toán khác.<br/><br/>(Các) lý do:",
        "wallet-payment-phone-header":"Vui lòng điền (các) trường bắt buộc dưới đây để đảm bảo đơn hàng của bạn được giao thành công và thuận lợi.",
        "wallet-payment-submit-text": "Gửi",
        "invalid_cpf": "Vui lòng nhập số CPF hợp lệ.",
        "invalid_houseno": "Vui lòng nhập số nhà.",
        "invalid_bairro": "Vui lòng nhập Bairro.",
        "invalid_neighborhood": "Vui lòng nhập khu phố.",
        "something_wrong":"Đã xảy ra sự cố. ",
        "retry": "Thử lại",
        "invalid_consigneeId": "Mã người nhận hàng không hợp lệ",
        "phone_number" : "Số Điện Thoại:",
        "consignee_id" : "Mã Người Nhận Hàng:",
        "cpf" : "CPF (Đăng Ký Người Nộp Thuế Cá Nhân):",
        "pccc" : "PCCC (Mã Số Quản Lý Người Nhập Khẩu):",
        "invalid_code_id": "Mã hoặc ID không hợp lệ",
        "paymentMethod_not_return":"ID phương thức thanh toán không được trả về. Vui lòng thử lại sau.",
        "invalid_tax_id": "Mã hoặc Mã số thuế không hợp lệ",
        'invalid_district': 'Vui lòng nhập quận/huyện',
        'invalid_village': 'Vui lòng nhập xã/thôn',
        'invalid_apt_unit': 'Vui lòng nhập số căn hộ/số đơn vị',
        'invalid_county': 'Vui lòng nhập tỉnh',
        'invalid_ward': 'Vui lòng nhập phường',
        'invalid_address1': 'Vui lòng nhập địa chỉ',
        'unable_to_load_suggestions': 'Không thể tải các đề xuất',
        'searching': 'Đang tìm kiếm...',
        "record_not_found": "Không tìm thấy bản ghi",
        "invalid_zip_no": "4 chữ số.",
        "invalid_city_no": "Hãy nhập mã bưu chính trước.",
        "invalid_address_1_no": "Nhập địa chỉ và số nhà.",
        "invalid_zip_lu": "4 chữ số.",
        "invalid_city_lu": "Hãy nhập mã bưu chính trước.",
        "invalid_address_1_lu": "Nhập số nhà và tên đường.",
        "invalid_address_gr": "Hãy nhập địa chỉ đường của bạn.",
        "invalid_zip_gr": "5 chữ số.",
        "invalid_city_gr": "Bước vào thành phố.",
        "invalid_address_rs": "Nhập tên đường và số nhà.",
        "invalid_zip_rs": "5 chữ số.",
        "invalid_city_rs": "Nhập tên thị trấn hoặc thành phố."
}
