window.i18nData={
        "invalid_email":"請輸入有效的電子郵件地址。", 
        "invalid_fname":"名字無效。", 
        "invalid_lname":"姓氏無效。", 
        "invalid_phone":"電話號碼無效。", 
        "invalid_cc_month":"卡片到期月份無效。", 
        "invalid_cc_year": "卡片有效期年份無效。", 
        "invalid_cc":"信用卡號碼無效。", 
        "invalid_cvv":"卡片驗證值無效。", 
        "invalid_billing_fname":"帳單姓名不正確。", 
        "invalid_billing_lname":"帳單姓氏無效。", 
        "terms_agree":"請同意我們的條款與細則。",
        "required_fields":"必填欄位以紅色標示", 
        "required_fields2" :"請填寫以紅色標示的必填欄位。", 
        "no_orders":"目前沒有訂單。",
        "decline": "您的銀行正在阻止這筆付款。請繼續使用此瀏覽器，並回覆銀行發送的簡訊或電子郵件以完成此訂單。請確認您的資訊後再次嘗試，或改用其他付款方式。<br/><br/>原因：", 
        "no_item_in_cart": "您的購物車中沒有商品。請選擇要購買的商品。", 
        "page_reload":"關閉對話方塊後，頁面將會重新載入。",
        "invalid_exp_month":"請輸入有效的月份", 
        "invalid_exp_year":"請輸入有效的年份。", 
        "redirect_to_next":"正在跳轉至下一頁。",
        "processing":"正在處理請求...", 
        "paypal_processing":"請稍候，我們將帶您前往 PayPal 結帳頁面...", 
        "loading_msg":"您的商品正在預留中",
        "loading_msg_header": "請稍候",
        "select": "選擇", 
        "month" : "月份", 
        "year" : "年份",
        "january":"一月",
        "february":"二月",
        "march":"三月",
        "april":"四月",
        "may":"五月",
        "june":"六月",
        "july":"七月",
        "august":"八月",
        "september":"九月",
        "october":"十月",
        "november":"十一月",
        "december":"十二月",
        "klarna_billing_information": "帳單資訊",
        "klarna_email_placeholder":"首選電子郵件地址",
        "klarna_fname_placeholder":"名字",
        "klarna_lname_placeholder":"姓氏",
        "klarna_address1_placeholder":"街道地址",
        "klarna_address2_placeholder" :"公寓／套房／其他",
        "klarna_city_placeholder" :"城市",
        "klarna_state_province" :"--選擇州／省--",
        "klarna_postal_code" :"郵遞區號",
        "klarna_continue_with_text":"繼續",
        "trust_rating_popup_headertext": "您會如何評價您的購物體驗？",
        "trust_rating_popup_subtext":"您的回饋對我們非常重要",
        "trust_rating_buttontext": "提交",
        "required":"必填欄位",
        "invalid_exp_date": "過期日期無效",
        "error-msg-header":"付款失敗。請確認您的資料或使用其他付款方式。<br/><br/>原因：",
        "wallet-payment-phone-header":"請填寫以下必填欄位，以確保您的訂單能順利送達。",
        "wallet-payment-submit-text": "提交",
        "invalid_cpf": "請輸入有效的CPF號碼。",
        "invalid_houseno": "請輸入門牌號碼。",
        "invalid_bairro": "請輸入街區。",
        "invalid_neighborhood": "請輸入社區。",
        "something_wrong":"發生了錯誤。",
        "retry": "重試",
        "invalid_consigneeId": "收件人編號無效",
        "phone_number" : "電話號碼:",
        "consignee_id" : "收貨人編號:",
        "cpf" : "CPF（個人納稅人登記系統）：:",
        "pccc" : "PCCC（個人通關代碼）：",
        "invalid_code_id": "代碼或 ID 無效",
        "paymentMethod_not_return": "未傳回付款方式 ID。請稍後再試",
        "invalid_tax_id": "代碼或統一編號無效",
        'invalid_district': '請輸入地區',
        'invalid_village': '請輸入村莊',
        'invalid_apt_unit': '請輸入公寓／單位號碼',
        'invalid_county': '請輸入縣',
        'invalid_ward': '請輸入里',
        'invalid_address1': '請輸入地址',
        'unable_to_load_suggestions': '無法載入建議',
        'searching': '搜尋中...',
        "record_not_found": "找不到該記錄",
        "invalid_zip_no": "4 位數。",
        "invalid_city_no": "請先輸入郵遞區號。",
        "invalid_address_1_no": "請輸入街道名稱及門牌號碼。",
        "invalid_zip_lu": "4 位數。",
        "invalid_city_lu": "請先輸入郵遞區號。",
        "invalid_address_1_lu": "請輸入門牌號碼和街道名稱。"
}