window.i18nData={
        "invalid_email":"请输入有效的电子邮件地址。", 
        "invalid_fname":"名字无效。", 
        "invalid_lname":"姓氏无效。", 
        "invalid_phone":"电话号码无效。", 
        "invalid_cc_month":"卡片到期月份无效。", 
        "invalid_cc_year": "卡片有效期年份无效。", 
        "invalid_cc":"信用卡号无效。", 
        "invalid_cvv":"卡片验证值无效。", 
        "invalid_billing_fname":"账单中的名字无效。", 
        "invalid_billing_lname":"账单姓氏无效。", 
        "terms_agree":"请同意我们的条款和条件。",
        "required_fields":"必填字段以红色标出", 
        "required_fields2" :"请填写标红的必填字段。", 
        "no_orders":"没有订单。",
        "decline": "您的银行正在阻止此笔付款。请继续使用当前浏览器，并<b>回复银行的短信或电子邮件以完成此订单</b>。请核对您的信息后重试，或尝试使用其他支付方式。<br/><br/>原因：", 
        "no_item_in_cart": "您的购物车中没有商品。请选择要购买的商品。", 
        "page_reload":"关闭对话框后，页面将重新加载。",
        "invalid_exp_month":"请输入有效的月份", 
        "invalid_exp_year":"请输入有效的年份。", 
        "redirect_to_next":"正在跳转至下一页。",
        "processing":"正在处理请求...", 
        "paypal_processing":"请稍候，我们将为您跳转至 PayPal 结账页面……", 
        "loading_msg":"您的商品正在预留中",
        "loading_msg_header": "请稍等",
        "select": "选择", 
        "month" : "月份", 
        "year" : "年份",
        "january":"一月",
        "february":"二月",
        "march":"三月",
        "april":"四月",
        "may":"五月",
        "june":"六月",
        "july":"七月",
        "august":"八月",
        "september":"九月",
        "october":"十月",
        "november":"十一月",
        "december":"十二月",
        "klarna_billing_information": "账单信息",
        "klarna_email_placeholder":"首选电子邮件地址",
        "klarna_fname_placeholder":"名字",
        "klarna_lname_placeholder":"姓氏",
        "klarna_address1_placeholder":"街道地址",
        "klarna_address2_placeholder" :"公寓 / 套房 / 其他",
        "klarna_city_placeholder" :"城市",
        "klarna_state_province" :"-- 选择州/省 --",
        "klarna_postal_code" :"邮政编码",
        "klarna_continue_with_text":"继续",
        "trust_rating_popup_headertext": "您对这次购物体验的评价如何？",
        "trust_rating_popup_subtext":"您的反馈对我们非常重要",
        "trust_rating_buttontext": "提交",
        "required":"必填字段",
        "invalid_exp_date": "过期日期无效",
        "error-msg-header":"支付失败。请核对您的信息或尝试其他支付方式。<br/><br/>原因：",
        "wallet-payment-phone-header":"请填写以下必填信息，以确保您的订单顺利送达。",
        "wallet-payment-submit-text": "提交",
        "invalid_cpf": "请输入有效的CPF号码。",
        "invalid_houseno": "请输入门牌号。",
        "invalid_bairro": "请输入街区。",
        "invalid_neighborhood": "请输入社区。",
        "something_wrong":"出现了一些问题。",
        "retry": "重试",
        "invalid_consigneeId": "收货人 ID 无效",
        "phone_number" : "电话号码:",
        "consignee_id" : "收货人编号:",
        "cpf" : "CPF（个人纳税人登记系统）:",
        "pccc" : "PCCC（个人通关代码）：",
        "invalid_code_id": "代码或ID无效",
        "paymentMethod_not_return":"未返回支付方式 ID。请稍后再试。",
        "invalid_tax_id": "代码或税号无效",
        'invalid_district': '请输入区',
        'invalid_village': '请输入村',
        'invalid_apt_unit': '请输入公寓/单元号',
        'invalid_county': '请输入县',
        'invalid_ward': '请输入街道',
        'invalid_address1': '请输入地址',
        'unable_to_load_suggestions': '无法加载建议',
        'searching': '搜索中...',
        "record_not_found": "未找到该记录",
        "invalid_zip_no": "4位数。",
        "invalid_city_no": "请先输入邮政编码。",
        "invalid_address_1_no": "请输入街道地址和门牌号。",
        "invalid_zip_lu": "4位数。",
        "invalid_city_lu": "请先输入邮政编码。",
        "invalid_address_1_lu": "请输入门牌号和街道名称。"
}